### ISSUE TITLE
Lesson skip is patched

### ISSUE THREAD

**Issue by Quintinox** [cupiditys/iReady-Overload#10]
Basically the title, lesson skip is patched and everything else im pretty sure.

**Comment by sneak599** [comment]
I just found this today and may be using it wrong but it still wont work with both trying it for my path stuff and teacher assigned. I did what the pop up said but it still wont work may just be my school chromebook though don't have access to my pc until tomorrow.

**Comment by HyperDiaper** [comment]
Can you please fix this Issue quick? I need to have 30 I-ready lessons due please help and fix.

**Comment by cupiditys** [comment]
yeah i know
the problem is pretty easy to fix in concept, but i cant seem to find any way to implement it

**Comment by Quintinox** [comment]
> maybe you can make a discord server for i-ready overload? then you can announce updates on there and possibly people may be able to help you as well

**Comment by cupiditys** [comment]
fixed, https://github.com/cupiditys/iReady-Overload/tree/main/lessonSkipper
