### ISSUE TITLE
Diagnostic HACK NOT Working. [Don't use diagnostic hack right now]

### ISSUE THREAD

**Issue by Sxri** [cupiditys/iReady-Overload#104]
Hello, the diagnostic hack to get all answers right doesn't work, I tried it and got in trouble with my teacher, (there were no flags for speed either) I got a 2ND-grade LEVEL at the end and my score was terrible. I knew it was definitely not working and there was a issue in the code from that or it was patched. Please fix this so us kids are able to do this without any bad issues, either that or I can script a diagnostic hack for free. (ALSO An idea is to make a AUTO skip lessons, so when you skip it continues, skips the next, one, gets the score on the test 100, then gives the coins and restarts the loop using the questions and redoing giving you coins super fast. if this is possible of corse) 

- If you would like me to help script a better working diagnostic hack let me know, their database it pretty open making it easy to change answers, then again they consistantly update the diagnostic changing the code so that hacks on the diagnostic dont work. 

Thank you,
~ Sxri

**Comment by cupiditys** [comment]
#108
