### ISSUE TITLE
Diagnostic

### ISSUE THREAD

**Issue by OnlyRail** [cupiditys/iReady-Overload#113]
Does the Diagnostic Hack work already?!?!???!! I need to do it asap. PLS LET ME KNOW AS SOON AS POSSIBLE

**Comment by cupiditys** [comment]
read #108

**Comment by OnlyRail** [comment]
damn are you gonna fix it

**Comment by cupiditys** [comment]
read what it says

**Comment by cupiditys** [comment]
cant fix it

**Comment by OnlyRail** [comment]
i did read

**Comment by cupiditys** [comment]
i mean you can turn it on just incase it does work but i'd try to answer them correctly anyways
