### ISSUE TITLE
whats scores are obtainable

### ISSUE THREAD

**Issue by Supamariobros** [cupiditys/iReady-Overload#114]
ok so with the lesson skipper im scared they will catch me cuz if i put "85" the questions may equal up the 86 in that range, so can u add a fix or tell me the scores that are obtainable with quizzes :)

**Comment by HypnoticLOL** [comment]
dude the school wont know just just use whatever u want they cant check all possible scores

**Comment by Supamariobros** [comment]
im kinda scared tho
owner can u confirm this?

**Comment by Supamariobros** [comment]
also another question can u get blocked by using the chrome web store exestion i dont want to get blocked lmao

**Comment by HypnoticLOL** [comment]
u wont get fucking blocked unless its old and dude stop being a bitch I have made a version of this menu ik how iready works the scores dont matter as long as 75+

**Comment by Supamariobros** [comment]
alright sorry

**Comment by HypnoticLOL** [comment]
hey this isnt my github but if youd get blocked he wouldnt realese it and if youd fuck up with scores he wouldnt let that happen if u try to set score as 101 it would go to 100 its not bad

**Comment by cupiditys** [comment]
i wouldn't say it matters also hypnotic u dont have to be such an asshole jesus
