### ISSUE TITLE
discord pls

### ISSUE THREAD

**Issue by Spertasplat** [cupiditys/iReady-Overload#116]
can u make a discord server and patreon please, also if u do make  a patreon and u get enough supporters hen maybe update ui? pls make a discord server though for ppl that wanna support u and what ur doing to get rid of this stupid ass i-ready

**Comment by cupiditys** [comment]
i don't have a discord nor do i think anyone would donate if i did something like that

also im not sure what you want the ui to be updated to? seems fine right now

**Comment by Spertasplat** [comment]
ik but it kinda looks simple if u want i can make a ui in visual studio and convert the code to javascript or whatever u use

**Comment by Spertasplat** [comment]
also another thing,

can u pllllsss make another button thats like skip lesson non-sus version or something and what it does is it skips the lesson but on the teachers log it shows up as it took more then 60 seconds, since me and my friend got caught in 4k and all most of our lessons had some pretty sus scores. ill work on a ui

**Comment by cupiditys** [comment]
just farm minutes before skipping, also you can choose your score

**Comment by Spertasplat** [comment]
no ik but it says i finsihed the lesson in 60 seconds

**Comment by Spertasplat** [comment]
farm minutes is a seperate thing

**Comment by cupiditys** [comment]
> no ik but it says i finsihed the lesson in 60 seconds

yeah because you didnt farm minutes before skipping
