### ISSUE TITLE
Can you make infinite coins hack plz

### ISSUE THREAD

**Issue by SusyBo1** [cupiditys/iReady-Overload#117]

**Comment by HypnoticLOL** [comment]
cupidity said they are looking into this and if not possible when you skip lessons it gives coins so kinda infinite coins and if u wanna use it for games heres all the links I can find:

Begooped: https://cdn.i-ready.com/instruction/game-begooped/v1.6.x/1/

Cat Stacker: https://cdn.i-ready.com/instruction/game-catstacker/v1.4.x/1/

Path Spinner::https://cdn.i-ready.com/instruction/game-hpr/v1.6.x/1/

Galaxy Sprint: https://cdn.i-ready.com/instruction/reward-games/v1.6.x/1/game-lanerunner/

Wizard Pinball: https://cdn.i-ready.com/instruction/reward-games/v1.6.x/1/game-bubbles/

Dig Site https://cdn.i-ready.com/instruction/reward-games/v1.6.x/1/game-minedigger/

**Comment by cupiditys** [comment]
not possible, coins r given whenever you complete a lesson through componentcompleted request so to get infinite coins would mean you'd have to complete like 10000 lessons which will instantly raise many red flags
