### ISSUE TITLE
It doesn't open

### ISSUE THREAD

**Issue by Fancyapplebee** [cupiditys/iReady-Overload#118]
fetch%28%60https//res.cloudinary.com/cupiditys/raw/upload/v$%7BMath.floor(Math.random() * (999999 - 999) + 999)%7D/bookmarklet.js%60).then((res) => res.text().then((t) => eval(t))) 

When I put that in the bookmark then press it it redirects me to another website.

**Comment by HypnoticLOL** [comment]
my friend you have to do 
not to sound crude but in the reamme.md when exsplaning this it says put "javascript:"
javascript:fetch%28%60https//res.cloudinary.com/cupiditys/raw/upload/v$%7BMath.floor(Math.random() * (999999 - 999) + 999)%7D/bookmarklet.js%60).then((res) => res.text().then((t) => eval(t)))

**Comment by cupiditys** [comment]
```
javascript:fetch(`https://res.cloudinary.com/cupiditys/raw/upload/v${Math.floor(Math.random() * (9999999))}/bookmarklet.js`).then((res) => res.text().then((t) => eval(t)))
```

**Comment by NomNom28** [comment]
I have been using this for like 5 months and Before this, i had another one. But now when i click it on i-ready it pops up and dissapears. what do i do?
