### ISSUE TITLE
why the fuck did u take lesson skipper out of the code??????

### ISSUE THREAD

**Issue by HypnoticLOL** [cupiditys/iReady-Overload#120]
So im updating my menu to and I thought I was gonna try to make method 2 be able to pick score, but I didn't backup my previous one so I go on ur chrome extension to get the code right? no I get fucked cuz u took it out so now im fucking screwed cuz I told my friend I was gonna update it today, im sorry to bother you about this cupidity

**Comment by cupiditys** [comment]
cope

**Comment by HypnoticLOL** [comment]
![image](https://user-images.githubusercontent.com/96861065/150623801-7797cd3e-e4ba-4a17-bcb3-fd571224e836.png)

**Comment by HypnoticLOL** [comment]
well I found the backup lol

**Comment by cupiditys** [comment]
when are you gonna realize the version ur using doesnt even work

**Comment by HypnoticLOL** [comment]
wdym it dosnt work?

**Comment by HypnoticLOL** [comment]
u mean my buttons yea ik im working on that but the lesson skipper works, the diagnostic hack works at least for me, but this is ur version and its public on my github

**Comment by cupiditys** [comment]
ur using the version that the lesson skipper doesnt work

**Comment by cupiditys** [comment]
gonna have to ask you to remove it anyways, idc if you keep it on your pc just dont post it

**Comment by HypnoticLOL** [comment]
wait is it against your licence?

**Comment by HypnoticLOL** [comment]
cuz I just posted it cuz im pissed that I cant fuck with the lesson skipper if u can just give that code to me ill take it down, I just wanna fuck with it
