### ISSUE TITLE
Lesson Skipper doesn't work for these type of lessons

### ISSUE THREAD

**Issue by xelnu** [cupiditys/iReady-Overload#121]
The lesson skipper doesn't work for these type of lessons, it doesn't matter tho, I can complete it, I'm just reporting this as a bug

https://user-images.githubusercontent.com/78057273/150689294-dcb507f7-8757-4054-aa27-184cbb083989.png

**Comment by cupiditys** [comment]
it does

**Comment by xelnu** [comment]
> it does

nope

https://user-images.githubusercontent.com/78057273/151250746-373785ed-d71f-4452-b095-a2a265f9a3ee.mp4

**Comment by cupiditys** [comment]
did you read what it said "to skip this lesson, close the lesson and click the skip button again" you proceeded to close the lesson, open it again and then click it
