### ISSUE TITLE
Request for a hack on XtraMath

### ISSUE THREAD

**Issue by X2isme** [cupiditys/iReady-Overload#123]
Xtra Math is a thing where u gotta do math for 10 mins each day, there is a hack but it isn't being updated and it doesn't work for multiplication, and I'm to lazy to do Xtra math so it would be nice to get a hack, like complete day, auto answer, and complete current level (from addition to subtraction kinda)

**Comment by X2isme** [comment]
idk if it makes sense to you lol

**Comment by cupiditys** [comment]
i dont have xtra math

**Comment by xelnu** [comment]
maybe edgenuity?

**Comment by cupiditys** [comment]
i dont have edgenuity either

**Comment by X2isme** [comment]
> i dont have edgenuity either

i can send you a account

**Comment by X2isme** [comment]
> > i dont have edgenuity either
> 
> i can send you a account

should i send the account to cupiditysxd@gmail.com

**Comment by cupiditys** [comment]
> > > i dont have edgenuity either
> > 
> > 
> > i can send you a account
> 
> should i send the account to [cupiditysxd@gmail.com](mailto:cupiditysxd@gmail.com)

sure

**Comment by X2isme** [comment]
> > > > i dont have edgenuity either
> > > 
> > > 
> > > i can send you a account
> > 
> > 
> > should i send the account to [cupiditysxd@gmail.com](mailto:cupiditysxd@gmail.com)
> 
> sure

Okay I sent the login info

**Comment by X2isme** [comment]
> > > > > i dont have edgenuity either
> > > > 
> > > > 
> > > > i can send you a account
> > > 
> > > 
> > > should i send the account to [cupiditysxd@gmail.com](mailto:cupiditysxd@gmail.com)
> > 
> > 
> > sure
> 
> Okay I sent the login info

Did you get the login?

**Comment by cupiditys** [comment]
how do you get to the multiplication ones theres only addition

**Comment by X2isme** [comment]
you need to get a whole thing correct


> how do you get to the multiplication ones theres only addition

**Comment by SharkiArthur** [comment]
x2isme your pfp reminds me of balls and a dick.
Sorry.

**Comment by X2isme** [comment]
> x2isme your pfp reminds me of balls and a dick. Sorry.

blame github - its randomly genorated and im to lazy to change it

**Comment by cupiditys** [comment]
would anyone actually care for this cuz if so ill make it

**Comment by HypnoticLOL** [comment]
> would anyone actually care for this cuz if so ill make it

if u dont I will but that would mean me spamming your dms for help

**Comment by SharkiArthur** [comment]
> > would anyone actually care for this cuz if so ill make it
> 
> if u dont I will but that would mean me spamming your dms for help

yes hyp is right

**Comment by cupiditys** [comment]
cant you just paste
`setInterval(() => {
    console.log(parseInt(document.getElementsByClassName("operand1")[0].innerHTML) + parseInt(document.getElementsByClassName("operand2")[0].innerHTML))
}, 500);`
into the console and type the answer it gives
and change the + to * for multiplication and obviously - for subtraction
