### ISSUE TITLE
Can't Skip Close Reading lessons [BUG]

### ISSUE THREAD

**Issue by SusyBo1** [cupiditys/iReady-Overload#124]
![image](https://user-images.githubusercontent.com/95867977/150988458-18b18411-f69d-409c-8e42-7f83ef7c0914.png)
![image](https://user-images.githubusercontent.com/95867977/150988515-ba484dda-3bee-4a27-a7c1-4a390f767ac6.png)

**Comment by cupiditys** [comment]
yeah it doesn't work for close reading

**Comment by WhatHaveIGottenInto2020** [comment]
just don't do close reading :)
