### ISSUE TITLE
Can you add a hack like Add Coins? or minutes?[FEATURE]

### ISSUE THREAD

**Issue by SusyBo1** [cupiditys/iReady-Overload#125]

**Comment by cupiditys** [comment]
coins isnt possible, minutes is

**Comment by WhatHaveIGottenInto2020** [comment]
they already did afk minutes

**Comment by SusyBo1** [comment]
> cupiditys already did afk minutes

Yeah but you have to wait :(

**Comment by Auzgame** [comment]
@SusyBo1 Listen, the minutes timer is stored in a webserver that will time how long your there. You can't hack into that but you can trick the server into thinking that you have a lesson opened which is what @cupiditys did.

**Comment by SusyBo1** [comment]
> @SusyBo1 Listen, the minutes timer is stored in a webserver that will time how long your there. You can't hack into that but you can trick the server into thinking that you have a lesson opened which is what @cupiditys did.

Oh, that sucks, sorry for wasting your time :(

**Comment by cupiditys** [comment]
> 

it's possbi

> @SusyBo1 Listen, the minutes timer is stored in a webserver that will time how long your there. You can't hack into that but you can trick the server into thinking that you have a lesson opened which is what @cupiditys did.

you can "hack" into it for an insta minutes hack, basically if you were to send 30 resume lesson requests with all different (valid) authorization headers and after a minute stop them all, you will have 30 minutes (i just don't know how to automate this)

**Comment by HypnoticLOL** [comment]
wouldnt that kinda be ddosing?

**Comment by cupiditys** [comment]
> wouldnt that kinda be ddosing?

no?????
