### ISSUE TITLE
Minunets hack

### ISSUE THREAD

**Issue by HypnoticLOL** [cupiditys/iReady-Overload#126]
> @SusyBo1 Listen, the minutes timer is stored in a webserver that will time how long your there. You can't hack into that but you can trick the server into thinking that you have a lesson opened which is what @cupiditys did.

you can "hack" into it for an insta minutes hack, basically if you were to send 30 resume lesson requests with all different (valid) authorization headers and after a minute stop them all, you will have 30 minutes (i just don't know how to automate this)

_Originally posted by @cupiditys in https://github.com/cupiditys/iReady-Overload/issues/125#issuecomment-1022543051_

Couldnt you have a function to turn off the thing to were if u have 2 iready it closes 1 and then have like 18 of them open and u could use a bookmarklet to activate it cuz it would be easier then pressing a button on the menu, or for it to be authorized you could make the menu get your authorization variable and inject it into summin so it would be counted as authorized?

**Comment by HypnoticLOL** [comment]
not authorization shit i ment transferKey

**Comment by cupiditys** [comment]
what

**Comment by HypnoticLOL** [comment]
couldnt you use this to authorize sum shit, idk im fucking tired
![Screenshot 2022-01-26 4 50 40 PM](https://user-images.githubusercontent.com/96861065/151260949-e56beddf-c2ed-4f01-8db6-04c16a30944d.png)

**Comment by cupiditys** [comment]
id delete that, you just posted your ip

**Comment by HypnoticLOL** [comment]
oh shit I leaked my vpn's ip
