### ISSUE TITLE
[FEATURE] Firefox addon support

### ISSUE THREAD

**Issue by Dangerdonny** [cupiditys/iReady-Overload#127]
Would it be possible to make a port for the extension for firefox? that would be cool. It dosen't have to be on the firefox store.

**Comment by cupiditys** [comment]
its not on firefox store but u can manually install it https://github.com/cupiditys/iReady-Overload/wiki/How-to-install#manually-installing-extension

**Comment by cupiditys** [comment]
steps are probably different tho

**Comment by Dangerdonny** [comment]
Yes they are, I think there would have to be an offical port for firefox due to the fact that firefox is not chromium based

**Comment by cupiditys** [comment]
nah I tried it works the same
