### ISSUE TITLE
It was working before now its not leasson skiper and minutes 

### ISSUE THREAD

**Issue by noob467** [cupiditys/iReady-Overload#129]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshot(s)/Video**

**Additional info**

**Comment by Ireadycoder** [comment]
you need to fill out the form in detail so he can help or i can

**Comment by cupiditys** [comment]
how am I supposed to help

**Comment by danielsdfr** [comment]
it wont let me skip the lessons :0

**Comment by Ireadycoder** [comment]
click skip lesson then when you go out press it again. Assuming this is your problem
