### ISSUE TITLE
[BUG] bruh just bruh

### ISSUE THREAD

**Issue by HypnoticLOL** [cupiditys/iReady-Overload#132]
This is ur fkin webstore exstenion
![Screenshot 2022-01-29 7 56 18 PM](https://user-images.githubusercontent.com/96861065/151683767-7d0f2ee0-984e-485d-9512-f46e9578b1da.png)

**Comment by cupiditys** [comment]
it got (falsely) taken down by curriculum associates so I just submitted an appeal
![1F27EC14-B3D9-4BC6-A2FD-FEA7694D5D8B](https://user-images.githubusercontent.com/66990287/151686130-8057b2df-f46b-4aa7-8b67-79580dec9866.jpeg)

**Comment by HypnoticLOL** [comment]
> it got (falsely) taken down by curriculum associates so I just submitted an appeal ![1F27EC14-B3D9-4BC6-A2FD-FEA7694D5D8B](https://user-images.githubusercontent.com/66990287/151686130-8057b2df-f46b-4aa7-8b67-79580dec9866.jpeg)

lol thats bulshit ur not invading copyright

**Comment by suckinsus** [comment]
you at like your not ruining a business and letting kids get away with false sores they have every right to take it down

**Comment by cupiditys** [comment]
> you at like your not ruining a business and letting kids get away with false sores they have every right to take it down

while I disagree about the “business” part (its not like I’m making money) sure they could of taken it down if it was for a valid reason but they took it down for a completely incorrect reason
