### ISSUE TITLE
chrome web store

### ISSUE THREAD

**Issue by OnlyRail** [cupiditys/iReady-Overload#133]
the chrome web store doesnt have a hack anymore, why?

**Comment by Ireadycoder** [comment]
prob got reported by the administration of iready, anyways all you gotta do is drag a file to install it so what's the issue?

**Comment by cupiditys** [comment]
got taken down by curriculum associates, contacted support to appeal just waiting for a response

**Comment by cupiditys** [comment]
update: google retarded and not putting back up so rip chrome store
