### ISSUE TITLE
Minute farm [BUG]

### ISSUE THREAD

**Issue by shanereportsissues** [cupiditys/iReady-Overload#134]
Bro whenever i minute farm for like 30 minutes or more with out tapping the screen it always exits me out of iready when i go to check my minutes and makes me log in again pls fix iit

**Comment by cupiditys** [comment]
https://github.com/cupiditys/iReady-Overload#how-to-avoid-being-afk-kicked

**Comment by SusyBo1** [comment]
@cupiditys can't you make the "Minute Farm" automatically enable "Anti-AFK" when you press it?

**Comment by cupiditys** [comment]
> @cupiditys can't you make the "Minute Farm" automatically enable "Anti-AFK" when you press it?

yea I already made a remake of minute farm and that’s added (ill release soon)
