### ISSUE TITLE
Lesson Skipper nor The Minutes Farmer Don't Work on Mastery Check [BUG]

### ISSUE THREAD

**Issue by honeyymxlk** [cupiditys/iReady-Overload#136]
**Describe the bug**
Okay so, the lesson skipper doesn't recognize the Mastery Check as a Lesson, and will not skip it nor will the minute farmer farm.

**To Reproduce**
Set up a teacher account and give the student account a Mastery Check, try to turn on the Lesson Skipper or Minute Farmer, Doesn't work.

**Expected behavior**
Lesson Skipper is supposed to skip the Mastery Check.
Minutes Farmer will not farm minutes.

**Screenshot(s)/Video**
![image](https://user-images.githubusercontent.com/96080365/151993604-65b47218-e6cb-4cbf-82c2-64c55569f6ca.png)

**Additional info**
There are two parts to the master check (on mine) never did it before though, might be different depending on the passage.

**Comment by cupiditys** [comment]
its for skipping lessons, hence the name “lesson” skipper (mastery checks don’t seem possible to make a skipper for but I’ve never really looked into it)
