### ISSUE TITLE
DO NOT USE

### ISSUE THREAD

**Issue by suckinsus** [cupiditys/iReady-Overload#137]
if you use lesson skip it'll show up as you did the lesson in a minute making it to easy for teachers to see who used 3 kids got suspended today and they just found out if you do use it afk for 20 mins then skip but it's not worth it if i ready is a (the 3 kids were using it on graded lessons) just don't use it

**Comment by cupiditys** [comment]
ive literally said this a billion times, if you still insta skip it then it’s your fault (im also adding a warning next release)

this is what it looks like for teachers, see how it says 1 minute bruh
![14BE6A06-F0CF-45F4-B824-957C6461F724](https://user-images.githubusercontent.com/66990287/152050134-fac3190a-11c0-49cf-8dea-e36b4c862382.jpeg)

**Comment by suckinsus** [comment]
do you think they may be adding something to deal with the hack 
![image](https://user-images.githubusercontent.com/98831157/152084850-985f21d0-a51a-453a-9d0c-dea7685c794e.png)

**Comment by cupiditys** [comment]
no

**Comment by cupiditys** [comment]
but i have a educator account ill check afterwards

**Comment by SusyBo1** [comment]
@cupiditys can you make it so that it's not suspicious when you instant complete lessons? (like make it automatically add minutes of our choice?)
