### ISSUE TITLE
[BUG]it was removed from the chrome store it says page not found and doesnt show up

### ISSUE THREAD

**Issue by jzxcracked** [cupiditys/iReady-Overload#138]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshot(s)/Video**

**Additional info**

**Comment by cupiditys** [comment]
curriculum associates got it falsely taken down and google staff are stupid so no more chrome web store sadly

**Comment by joshyboitheboi** [comment]
im 99% sure that me and a few friends were the reason it got taken down, school contacted i-ready, i-ready contacted google. went down like 20 mins after. also got written up and they said i commited a "felony".

**Comment by cupiditys** [comment]
very sad

**Comment by SusyBo1** [comment]
Sad :'(

**Comment by HypnoticLOL** [comment]
f
