### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Ireadycoder** [cupiditys/iReady-Overload#14]
do you care if i make this into a extension or are u planning to?

**Comment by cupiditys** [comment]
im planning to later but you can do it now if you want

**Comment by cyber1109** [comment]
im confused

**Comment by cupiditys** [comment]
> im confused

about what

**Comment by cyber1109** [comment]
on the lesoon skiper did you do the exteson

**Comment by cupiditys** [comment]
no not yet you have to do it manually by following the steps
