### ISSUE TITLE
yo since I took it down

### ISSUE THREAD

**Issue by HypnoticLOL** [cupiditys/iReady-Overload#140]
when ever u realese a new version could you give me the update cuz like with lesson skipper imma make a auto lesson skipper with no alerts so pls at least give me lesson skipper updates with minuite farming and diagnostic shit I dont care about I only care about lesson skipper

**Comment by cupiditys** [comment]
wdym “auto lesson skipper”

**Comment by cupiditys** [comment]
if you mean it auto clicks back into the lesson then good luck making that

**Comment by cupiditys** [comment]
harder than you think

**Comment by HypnoticLOL** [comment]
fuck i was gonna make it auto go in and out of the lessons and give you 100%s

**Comment by HypnoticLOL** [comment]
i have the code that should work so now and ik its hard because you gave me this code a while ago and even you said u didnt know
