### ISSUE TITLE
Make it Enable Anti-AFK automaticaly when you use Farm Minutes [FEATURE]

### ISSUE THREAD

**Issue by SusyBo1** [cupiditys/iReady-Overload#142]
plz add, it keeps on kicking me out when I use it and I forget to paste anti-AFK

**Comment by HypnoticLOL** [comment]
not tryna apertize here but my menu has auto anti afk

**Comment by cupiditys** [comment]
> plz add, it keeps on kicking me out when I use it and I forget to paste anti-AFK

already will be in next release

**Comment by HypnoticLOL** [comment]
> > plz add, it keeps on kicking me out when I use it and I forget to paste anti-AFK
> 
> already will be in next release

wait when are you is gonna be the next release cuz im getting hyped to see what you add

**Comment by SusyBo1** [comment]
> not tryna apertize here but my menu has auto anti afk

@HypnoticLOL Oh I didn't know thx, I have your menu in my bookmark ;)
