### ISSUE TITLE
0.1.8 extension doesnt work( I click on skip lesson or farm minutes and it doesnt work.) but if you copy and paste into console diff it works . [BUG]

### ISSUE THREAD

**Issue by DaniilnoIready** [cupiditys/iReady-Overload#150]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshot(s)/Video**

**Additional info**

**Comment by cupiditys** [comment]
is it bookmarklet or extension

**Comment by DaniilnoIready** [comment]
I think extension

**Comment by cupiditys** [comment]
is there any errors in console

**Comment by cupiditys** [comment]
nvm I know what’s wrong im retarded

**Comment by cupiditys** [comment]
should be fixed now

**Comment by DaniilnoIready** [comment]
lmao ur not retarded since you made this life saving program. :) Thank you its fixed
