### ISSUE TITLE
[BUG] Update it from Manifest V2 to V3

### ISSUE THREAD

**Issue by voidbakersd** [cupiditys/iReady-Overload#152]
Hello! im trying to keep this secret from my school but yet distribute it, so im trying to upload it to the chrome store!

Just try and upload it, google will give you a error saying it needs to be updated to Manifest V3 

I just would like to work and probably have 50-200 new kids no longer doing i-ready!

![image](https://user-images.githubusercontent.com/98135729/152461039-3ce29e8a-1ae2-419d-9227-08cf70378433.png)

**Comment by voidbakersd** [comment]
also yes i payed the $5 and im giving this out for free, guess its a public service lol
(also im happy af what you do its baller)

**Comment by cupiditys** [comment]
ive already uploaded it to chrome web store, they took it down for breaking tosw

**Comment by cupiditys** [comment]
> ive already uploaded it to chrome web store, they took it down for breaking tos

**Comment by voidbakersd** [comment]
i dont mind but could you update it to Manifest V3 its low grade shiiiit

**Comment by cupiditys** [comment]
ill update the day before chrome removes support

**Comment by voidbakersd** [comment]
it is removed support for uploading new stuff

**Comment by cupiditys** [comment]
you can still manually add it
