### ISSUE TITLE
Multiple farm minute buttons/farm speed setting

### ISSUE THREAD

**Issue by jat354155** [cupiditys/iReady-Overload#153]
The farm minutes button is kinda slow, 

Having multiple browsers open at once can actually speed up minute gain by a lot, 1 minute per 30 seconds, Sheeeesh! the fact that you can't be in a lesson gaining minutes yourself and farm is really sad.

Could you possibly add a speed setting to the minute farm?

**Comment by cupiditys** [comment]
yea I know, not sure how to automate that though

**Comment by HypnoticLOL** [comment]
> yea I know, not sure how to automate that though
couldnt you do it through like a proxy and have multiple servers and them being able to login to the users account with a cookie and farm minuites that way? I have a proxy server if u need it

**Comment by cupiditys** [comment]
> > yea I know, not sure how to automate that though
> 
> couldnt you do it through like a proxy and have multiple servers and them being able to login to the users account with a cookie and farm minuites that way? I have a proxy server if u need it

no

**Comment by HypnoticLOL** [comment]
> > > yea I know, not sure how to automate that though
> > 
> > 
> > couldnt you do it through like a proxy and have multiple servers and them being able to login to the users account with a cookie and farm minuites that way? I have a proxy server if u need it
> 
> no

damn that sucks

**Comment by cupiditys** [comment]
i actually know how to do this now, maybe soon :tm:
