### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JordanMcshane23** [cupiditys/iReady-Overload#155]
On iReady Overload, these type of lessons won't work for the "Skip this lesson " option. Am I doing a wrong step here or is it a bug.
![Screenshot (39)](https://user-images.githubusercontent.com/69442562/152622745-0e86f49d-2043-4eed-94b4-f68bc61ddab7.png)
]

**Comment by cupiditys** [comment]
close the lesson and press the skip button
