### ISSUE TITLE
Cannot change score on quiz

### ISSUE THREAD

**Issue by minsn** [cupiditys/iReady-Overload#156]
I tried changing the score on my reading quiz to 75% and it instead passed the quiz but the score was 100% instead of 75% so I tried it on a math lesson and the same thing happened I set it to 85% and it passed the quiz with 100%

**Comment by cupiditys** [comment]
are you putting the % at the end

**Comment by HypnoticLOL** [comment]
based on the information your giving and cupiditys answer, dont put % at the end

**Comment by minsn** [comment]
> g the % at the end

nope wasn't ill try that next week when I get new lessons mb

**Comment by minsn** [comment]
> are you putting the % at the end

Nope i wasn't ill try that when i get new lessons next week mb

**Comment by cupiditys** [comment]
> > are you putting the % at the end
> 
> Nope i wasn't ill try that when i get new lessons next week mb

no i mean you aren't supposed to because i added a check that if what you put in isnt a valid number it ignores it and falls back to 100

**Comment by cupiditys** [comment]
because before if you put in something that isnt a number it would completely break ur iready and lock you from opening lessons

**Comment by minsn** [comment]
> > > are you putting the % at the end
> > 
> > 
> > Nope i wasn't ill try that when i get new lessons next week mb
> 
> no i mean you aren't supposed to because i added a check that if what you put in isnt a valid number it ignores it and falls back to 100

oh i thought that 85% was the score you got when you got one answer wrong but ig its not so ill try 75% which i know for sure is the score you get for 2 answers wrong

**Comment by cupiditys** [comment]
> > > > are you putting the % at the end
> > > 
> > > 
> > > Nope i wasn't ill try that when i get new lessons next week mb
> > 
> > 
> > no i mean you aren't supposed to because i added a check that if what you put in isnt a valid number it ignores it and falls back to 100
> 
> oh i thought that 85% was the score you got when you got one answer wrong but ig its not so ill try 75% which i know for sure is the score you get for 2 answers wrong

I realized yesterday I actually messed up, download new version and itll be fixed
