### ISSUE TITLE
I dont know how to download the new update

### ISSUE THREAD

**Issue by TJpot** [cupiditys/iReady-Overload#157]
I dont know how to update .It Keeps telling me do you want to download the new update.I have the extension but i dont know how to update it

**Comment by TJpot** [comment]
to be exact is says this "An update is available, would you like to open the github? (your version: 0.1.7; current version: 0.1.8)"

**Comment by HypnoticLOL** [comment]
just get the new bookmarkket

**Comment by cupiditys** [comment]
https://github.com/cupiditys/iReady-Overload/wiki/How-to-install
