### ISSUE TITLE
[BUG] My iready is 315% done and not letting me finish it

### ISSUE THREAD

**Issue by Princessyummo** [cupiditys/iReady-Overload#158]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshot(s)/Video**

**Additional info**

**Comment by HypnoticLOL** [comment]
bro how is anyone gonna help fucking fill out the forum and dont just leave it blank

**Comment by cupiditys** [comment]
theres a reason a made an issue template, ur supposed to fill it out
