### ISSUE TITLE
[BUG] does not choose ur score

### ISSUE THREAD

**Issue by masssydoosy** [cupiditys/iReady-Overload#164]
**Describe the bug** if your specific score is chosen like 88 or 92 or 67 or 75 etc, does not put that and puts default 100 not really needed to fix but can make teachers suspect cause its impossible to get a perfect score without cheating websites for very single lesson Home or school. so yes

**Comment by masssydoosy** [comment]
@cupiditys

**Comment by HypnoticLOL** [comment]
u know u can delete the 100 and put those scores?

**Comment by masssydoosy** [comment]
I did
88 and 92 and it came up at 100 and i press OK

**Comment by masssydoosy** [comment]
@HypnoticLOL

**Comment by HypnoticLOL** [comment]
did u put % after?

**Comment by masssydoosy** [comment]
you sure it needs that? cause before i did not put % and it put my score

**Comment by HypnoticLOL** [comment]
naw u shouldnt do that just checking if u did

**Comment by masssydoosy** [comment]
kk

**Comment by HypnoticLOL** [comment]
what exsactly did u put in at the first time?

**Comment by masssydoosy** [comment]
(88) as like 1 wrong

**Comment by masssydoosy** [comment]
without parentheses

**Comment by HypnoticLOL** [comment]
shit, lemme troubleshoot for a sec

**Comment by masssydoosy** [comment]
kk

**Comment by HypnoticLOL** [comment]
what method were u using? method 1 or 2

**Comment by masssydoosy** [comment]
none chrome extension

**Comment by masssydoosy** [comment]
not sure which chrome extension it is as method

**Comment by HypnoticLOL** [comment]
that still has method 1 and 2. do you have to press skip 2 times  or 1

**Comment by masssydoosy** [comment]
once for the instruction once for the quiz

**Comment by masssydoosy** [comment]
so i guess 2

**Comment by HypnoticLOL** [comment]
ok so thats method 1, method 2 usually has the problems so I know what to do I think lemme try summin

**Comment by masssydoosy** [comment]
ok

**Comment by HypnoticLOL** [comment]
wtf ok imma try fixing this problem cuz I think theres a problem maybe im just a dumb ass

**Comment by masssydoosy** [comment]
lol ok

**Comment by HypnoticLOL** [comment]
u doing it like this?
![Screenshot 2022-02-06 6 24 00 PM](https://user-images.githubusercontent.com/96861065/152710071-608ad1c6-7f32-44cf-84d5-c81ce981c1bc.png)

**Comment by masssydoosy** [comment]
yes

**Comment by masssydoosy** [comment]
exactly

**Comment by masssydoosy** [comment]
try skip

**Comment by HypnoticLOL** [comment]
it gives me a error lol I broke my iready, imma fuck with it sum more

**Comment by masssydoosy** [comment]
ok i hope its not p broken

**Comment by HypnoticLOL** [comment]
k I got it to skip waiting for the last question

**Comment by masssydoosy** [comment]
k

**Comment by HypnoticLOL** [comment]
what the fuck... ?

**Comment by masssydoosy** [comment]
?

**Comment by HypnoticLOL** [comment]
100%...

**Comment by masssydoosy** [comment]
yes sir thats what i am reportin

**Comment by HypnoticLOL** [comment]
wait let me try my menu

**Comment by masssydoosy** [comment]
ok

**Comment by HypnoticLOL** [comment]
HOLY SHIT IREADY FIXED MY MENU TO XD

**Comment by masssydoosy** [comment]
lol

**Comment by HypnoticLOL** [comment]
bro thats funny I just started making my menu

**Comment by masssydoosy** [comment]
now you must make some changes

**Comment by masssydoosy** [comment]
also coincidental

**Comment by HypnoticLOL** [comment]
naw I just have to obfusicate better

**Comment by masssydoosy** [comment]
ok lol

**Comment by masssydoosy** [comment]
bruh this is the longest issue ive ever seen 45

**Comment by HypnoticLOL** [comment]
holy shit yea this shouldnt go on like this u got discord?

**Comment by masssydoosy** [comment]
yes i do heres my tag/id Master.#2841

**Comment by HypnoticLOL** [comment]
sent friends request

**Comment by HypnoticLOL** [comment]
@cupiditys  u can take it from here im crying about this I dont know how to fix this

**Comment by cupiditys** [comment]
im assuming its because i added this
```
if (!Number.isInteger(scoreInput)) {
    scoreInput = 100
}
```
basicially checks if input is not a number and if not it falls back to 100%, maybe doesnt work properly

**Comment by cupiditys** [comment]
yea thats definitely the reason why 
i didn't realize the prompt method always returns as a string even if u put all numbers

**Comment by masssydoosy** [comment]
imagine forgetting the 2nd 0... that would be very bad and hard to explain

**Comment by cupiditys** [comment]
alr fixed

**Comment by HypnoticLOL** [comment]
im a stupid ass
