### ISSUE TITLE
ur right

### ISSUE THREAD

**Issue by HypnoticLOL** [cupiditys/iReady-Overload#166]
u can get blocked I made summin to were u can get blocked instantly lol, (this was the intended outcome as I would like to troll friends)
![145728509-a9e54f52-539e-46aa-adaf-a6393767b02f](https://user-images.githubusercontent.com/96861065/152721856-61250035-9cf7-47cf-895a-3ce997ccff94.png)

**Comment by cupiditys** [comment]
how and also that image looks suspiciously similar to the one in #49

**Comment by HypnoticLOL** [comment]
lol just changes login screen with exstenion thats why the look
