### ISSUE TITLE
[BUG] Crashing

### ISSUE THREAD

**Issue by TNT599** [cupiditys/iReady-Overload#169]
**Describe the bug**
Overload opens for a second or two, crashes, and can not be reopened
**To Reproduce**
Open Overload
**Expected behavior**
Should stay up
**Screenshot(s)/Video**
https://streamable.com/d3r3qc
**Additional info**

**Comment by cupiditys** [comment]
download the newest version they patched old one

**Comment by TNT599** [comment]
Okay, thanks.

**Comment by HypnoticLOL** [comment]
> Okay, thanks.

btw u can delete the "Afk" bookmarklet its unneeded now beging 0.1.8
