### ISSUE TITLE
I drag the file onto chrome extensions but still won't install. Dev mode is turned on

### ISSUE THREAD

**Issue by Kenjeye** [cupiditys/iReady-Overload#17]

**Comment by cupiditys** [comment]
could you record a video and send it?

**Comment by Kenjeye** [comment]
I figured the installing part6 but now when ever i go into i-ready the menu only pops up for a second. Then i try to hit ctrl+z to bring it back up but it won't work. Here's a v

https://user-images.githubusercontent.com/95196466/143797023-302cbc56-a0b4-4483-b7f9-fd1280bae85a.mp4

id

**Comment by cupiditys** [comment]
download the newest version

**Comment by cyber1109** [comment]
> download the newest version

where is the exteonson ?

**Comment by cyber1109** [comment]
where to download the new one
?

**Comment by cyber1109** [comment]
???

**Comment by Barnac1ed** [comment]
> where to download the new one ?

https://github.com/cupiditys/iReady-Overload/blob/main/chromeExtension.zip

on the page above the empty code read in the top right there is a download button

**Comment by haloblaster** [comment]
@Barnac1ed is it safe to use lesson skipper

**Comment by cyber1109** [comment]
> > where to download the new one ?
> 
> https://github.com/cupiditys/iReady-Overload/blob/main/chromeExtension.zip
> 
> on the page above the empty code read in the top right there is a download button

it dose not work
