### ISSUE TITLE
holy fuck

### ISSUE THREAD

**Issue by HypnoticLOL** [cupiditys/iReady-Overload#171]
<p style="color: blue; font-size10;">so my class stopped doing iready and my teacher works for iready for some reason she supports this "educational modifying" and is helping me with my menu by giving me basically ireadys code and tells me how to modify it<p>

**Comment by cupiditys** [comment]
bro why tf are you lying about this it makes 0 sense in the absolute slightest

**Comment by HypnoticLOL** [comment]
idk my teachers just helping me hack since she thinks its for educatinal purposes like thing like PHEx

**Comment by HypnoticLOL** [comment]
and I was hella tired

**Comment by cupiditys** [comment]
> idk my teachers just helping me hack since she thinks its for educatinal purposes like thing like PHEx

no they aren’t bro and if they somehow actually are then I wanna talk to them

**Comment by HypnoticLOL** [comment]
she works for iready in the summer since she hella poor

**Comment by HypnoticLOL** [comment]
and I didnt mean teachers just 1

**Comment by cupiditys** [comment]
> and I didnt mean teachers just 1

so how do I talk to her

**Comment by HypnoticLOL** [comment]
idk

**Comment by HypnoticLOL** [comment]
well ik u cant today cuz I skipped

**Comment by cupiditys** [comment]
yea totally bro

**Comment by SharkiArthur** [comment]
bro how fucking fake could this be hyponic atleast make it sound better

**Comment by HypnoticLOL** [comment]
bro I skipped today and im skipping tommorow maybe ill be at school thursday but idfk im a dumb ass 6th grader and I dont give a flying fuck

**Comment by cupiditys** [comment]
> bro I skipped today and im skipping tommorow maybe ill be at school thursday but idfk im a dumb ass 6th grader and I dont give a flying fuck

why are you skipping 6th grade bruh it is beyond easy

**Comment by cupiditys** [comment]
i sat on my phone every class in 6th and had straight a’s

**Comment by SharkiArthur** [comment]
> 

I seee, now tell me how many absences u got 20+ = Summer school

**Comment by SharkiArthur** [comment]
and why is this marked as a question.

**Comment by HypnoticLOL** [comment]
first I never marked this as a question I marked it as blank, second
![Screenshot 2022-02-08 10 41 35 PM](https://user-images.githubusercontent.com/96861065/153123461-96ea0efb-6ebc-486d-8499-f55944be214e.png)

**Comment by HypnoticLOL** [comment]
homeroom absences counts for all classes

**Comment by HypnoticLOL** [comment]
> > bro I skipped today and im skipping tommorow maybe ill be at school thursday but idfk im a dumb ass 6th grader and I dont give a flying fuck
> 
> why are you skipping 6th grade bruh it is beyond easy

so I can watch one peice

**Comment by SharkiArthur** [comment]
24 absences holy shit I got 2 only u getting summer school my friend and wtf are ur parents doing
<img width="331" alt="Screen Shot 2022-02-09 at 12 08 25 AM" src="https://user-images.githubusercontent.com/91421571/153125819-7bd44770-c191-4414-937d-237c91375ffe.png">

t

**Comment by HypnoticLOL** [comment]
my parents think im sick XD

**Comment by SharkiArthur** [comment]
and ofc the grading system is down yes idc I am sharing my county 
<img width="863" alt="Screen Shot 2022-02-09 at 12 11 10 AM" src="https://user-images.githubusercontent.com/91421571/153126157-687dd89f-2f01-4ec7-b72d-893d5ef3db6e.png">

**Comment by SharkiArthur** [comment]
wait wait chill your going to get summer school and maybe stop or your parents will find out 1 time and kill you

**Comment by HypnoticLOL** [comment]
yo if u wanna ask me question or rlly and thing add me on discord @HypnoticLOL#7455

**Comment by SharkiArthur** [comment]
<img width="1119" alt="Screen Shot 2022-02-09 at 12 15 21 AM" src="https://user-images.githubusercontent.com/91421571/153126418-eb97ccfd-f61a-4d1a-b6f8-b2227ee1e870.png">
all bro these grades were trash when I was in 6th

**Comment by SharkiArthur** [comment]
dam closed this
