### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by by1egend251** [cupiditys/iReady-Overload#172]
**Describe the bug**
ctrl + z doesnt hide panel
**To Reproduce**
whenever i click ctrl + z it does not hide it, it works sometimes but not always
**Expected behavior**
close panel whenever i hit ctrl + z
**Screenshot(s)/Video**
on school computer right now
**Additional info**

**Comment by HypnoticLOL** [comment]
yea sometimes it dosnt work in a iready lesson its a glitch bc of iframe. rn dosnt look like a possible fix
