### ISSUE TITLE
[BUG] Does not let me drag the file on the extensions

### ISSUE THREAD

**Issue by wtfstretch** [cupiditys/iReady-Overload#175]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshot(s)/Video**

**Additional info**

**Comment by wtfstretch** [comment]
does not let me drop the iready file into the extensions

**Comment by SharkiArthur** [comment]
u really are fucked extract the fucking folder mf

**Comment by SharkiArthur** [comment]
and you don't drag it u fucking turn on dev mode and click load unpacked and select it mf

**Comment by HypnoticLOL** [comment]
> and you don't drag it u fucking turn on dev mode and click load unpacked and select it mfing dumb ass

yea you better be nicer lol if u continue to be a dick cupidity might block u from commenting

**Comment by cupiditys** [comment]
> does not let me drop the iready file into the extensions

did you extract the zip to get iready overload folder first

**Comment by wtfstretch** [comment]
how do i do that?

**Comment by wtfstretch** [comment]
do you have discord or something if u do add me so u can help me iits ! stretch#3617

**Comment by wtfstretch** [comment]
nvm it works
