### ISSUE TITLE
skip glitch maybe

### ISSUE THREAD

**Issue by TrixFN** [cupiditys/iReady-Overload#177]
when i go to skip it just keeps saying "To skip this lesson, close the lesson and click the skip button again."it says skipping lesson but its not even if i close the lesson and then go back it still shows when i close iready it goes to normal but it still doesnt work maybe its the lesson idk

**Comment by HypnoticLOL** [comment]
your stopose to read the popups, or when u close it press skip again. if it closes by itself just go back in.

**Comment by Ireadycoder** [comment]
stay on the home page then click skip dont click the lesson

**Comment by HypnoticLOL** [comment]
well you press skip in the lesson, then leave the lesson press skip again then go into the lesson and it should be skipped, you will have to do the last lesson tho, it will count the last one as correct
