### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by wtfstretch** [cupiditys/iReady-Overload#178]
**Describe the feature**

**Additional context**

**Comment by wtfstretch** [comment]
Make a khan acadamy hack

**Comment by cupiditys** [comment]
why

**Comment by SharkiArthur** [comment]
there are plenty

**Comment by wtfstretch** [comment]
where?

**Comment by SharkiArthur** [comment]
https://www.google.com/search?q=han+acadamy+hack&sourceid=chrome&ie=UTF-8
thats enough for you to understand,

**Comment by cupiditys** [comment]
https://github.com/adubov1/khanacademy_bot https://youtu.be/dQSZXA77kp8

**Comment by wtfstretch** [comment]
that answer key doesnt always show the answer and sometimes it isnt right ive tried it
