### ISSUE TITLE
[BUG] Ctritcal

### ISSUE THREAD

**Issue by Auzgame** [cupiditys/iReady-Overload#182]
Hey, Cuptiidy It's me again. This time I'm reporting that the hack isn't working rn because iready just updated their site and has now blocked it.  I'm proposing a simple fix to just change the div element to a section element. Otherwise just try and use the bookmarklet and you will see an error in the console.

**Comment by poopyhead121** [comment]
@Auzgame make a pull request if you can somehow get it working, i need to get iready done in 5 hours

**Comment by cupiditys** [comment]
i already have it fixed will release soon enough

**Comment by cupiditys** [comment]
updated
