### ISSUE TITLE
I ready overload doesn't work !!!

### ISSUE THREAD

**Issue by jeremy042** [cupiditys/iReady-Overload#184]
so every time I use the extension or put the code on console on I ready it pop up and then vanishes what is happing.
 plz help!!

**Comment by wtfstretch** [comment]
idk iready found out i think

**Comment by cupiditys** [comment]
iready patched it they do this on a weekly basis bruh ill fix later just don’t use rn

**Comment by wtfstretch** [comment]
aight can u tell us when u fix it doe

**Comment by cupiditys** [comment]
updated
