### ISSUE TITLE
[BUG]  I-Ready UI keeps closing on startup (patched ig.)

### ISSUE THREAD

**Issue by Q1ddz** [cupiditys/iReady-Overload#186]
**Describe the bug**
GUI closes after startup

**To Reproduce**
Just go to login.i-ready.com.

**Expected behavior**
UI is supposed to be there, CTRL-Z to open or close.

**Screenshot(s)/Video**
None needed.

**Additional info**
Try to patch this please, I need my 30 minutes of I-Ready for the day.

**Comment by HypnoticLOL** [comment]
patched prob be fixed soon

**Comment by Doppio-Frog** [comment]
This is happening to me as-well, is it working for you now?

**Comment by SharkiArthur** [comment]
nope

**Comment by cupiditys** [comment]
updated

**Comment by navoman123** [comment]
it started again its not working it does the same problem
