### ISSUE TITLE
[FEATURE] Add support for more browsers

### ISSUE THREAD

**Issue by EmreTech** [cupiditys/iReady-Overload#188]
**Describe the feature**

Add support for more browsers with iReady Overload. Some browsers these days use Chromium and I think they keep the Chrome Extensions system. However, there are still browsers that aren't based on Chrome at all: like Firefox.

**Comment by cupiditys** [comment]
u can still use bookmarklet if youre on firefox

**Comment by EmreTech** [comment]
Hm okay I'll try that out

**Comment by EmreTech** [comment]
I tried that, and when I click on it, the menu appears then disappears almost immediately.

**Comment by EmreTech** [comment]
I'm going to go open another issue about this.
