### ISSUE TITLE
Lesson skipper won’t work

### ISSUE THREAD

**Issue by comradeduck** [cupiditys/iReady-Overload#192]
It won’t work I don’t have proof but
Please help

**Comment by comradeduck** [comment]
Ps I use the bookmarklet for school chrome book

**Comment by comradeduck** [comment]
Thanks bro you the best

**Comment by forst-c** [comment]
so is it fucked or is it not?

**Comment by cupiditys** [comment]
yea almost fixed

**Comment by cupiditys** [comment]
fixed
