### ISSUE TITLE
[BUG] this shit make iready crash or become unresponsive a ton this should be a priority fix  

### ISSUE THREAD

**Issue by 1996-300zx-twin-turbo** [cupiditys/iReady-Overload#194]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshot(s)/Video**

**Additional info**

**Comment by wtfstretch** [comment]
its for me too

**Comment by cupiditys** [comment]
only crashes if you open inspect element/console whatever

**Comment by 1996-300zx-twin-turbo** [comment]
prolly my laptop tbh
