### ISSUE TITLE
[BUG] Menu disappears immediately 

### ISSUE THREAD

**Issue by EmreTech** [cupiditys/iReady-Overload#198]
**Describe the bug**
After clicking on the bookmarklet, the menu shows for 1 second then disappears quickly.

**To Reproduce**
Use the bookmarklet (not sure if the Chrome Extension has the same problem)

**Expected behavior**
The menu shows until I hide it with Control+Z

**Screenshot(s)/Video**
https://user-images.githubusercontent.com/50607143/153729549-66266a22-5ac7-4dfb-9a88-acd4e352c5cb.mov

**Comment by cupiditys** [comment]
i cant see the video because it wont load but im going to assume ur using an old version and need to update

**Comment by EmreTech** [comment]
I don't think I am

**Comment by HypnoticLOL** [comment]
heres his video

https://user-images.githubusercontent.com/96861065/153730825-8fbfda72-36d7-414f-8445-733596f9317a.mp4

**Comment by illusions-creator** [comment]
having the same issue with it even with the latest version. Might be a problem with firefox

**Comment by EmreTech** [comment]
Maybe

**Comment by cupiditys** [comment]
i just tested and it worked fine

**Comment by SharkiArthur** [comment]
works fine

**Comment by illusions-creator** [comment]
Happens to me to:

https://user-images.githubusercontent.com/73310622/153733663-8095bac1-dbdf-4d0a-b0bb-0b471e458f11.mp4

**Comment by cupiditys** [comment]
can you try using this version https://github.com/cupiditys/iReady-Overload/blob/main/bookmarklet.txt

**Comment by illusions-creator** [comment]
same results :/

**Comment by cupiditys** [comment]
yea i have literally 0 clue it works for everyone i've asked

**Comment by cupiditys** [comment]
u can try going on chrome if you really want

**Comment by SharkiArthur** [comment]
IT WORKS FINE YOUR ALL YOUR INTERNET

**Comment by SharkiArthur** [comment]
If you really want it to work try this version (I edited Cupids credit goes to him) https://github.com/SharkiArthur/cupiditysmenurevised

**Comment by illusions-creator** [comment]
yea that doesn't work. To remind you were talking about different browsers not being supported. The browser I and EmreTech are using is firefox.

**Comment by cupiditys** [comment]
yea for some reason it only doesn't work on firefox, no clue why
either switch to chrome or edge sorry
