### ISSUE TITLE
[BUG] Animated Lessons do not skip.

### ISSUE THREAD

**Issue by hondarad** [cupiditys/iReady-Overload#201]
Animated Lessons with characters that talk or interact with the questions do not get skipped.

Go into an Animated Lesson, Press on "Skip Lesson" and it will not skip any animated lesson at all. 

Skip an Animated Lesson

https://user-images.githubusercontent.com/99567033/153733966-898bdcbc-6980-4af3-aa26-46ec7f273a32.mp4

**Comment by illusions-creator** [comment]
did you read the alert at all.

**Comment by hondarad** [comment]
OH I was dumb. I thought you had to go into the lesson after it pops up and click it again. Thank you for your help!!

**Comment by cupiditys** [comment]
> OH I was dumb. I thought you had to go into the lesson after it pops up and click it again. Thank you for your help!!

depends on the lesson, some you have to do that
