### ISSUE TITLE
[BUG] I am not trolling btw, anyways my lesson skipper keeps on saying I'm already skipping a lesson ever though I'm not

### ISSUE THREAD

**Issue by NinTheCoolGuy** [cupiditys/iReady-Overload#203]
Describe the Bug
I start the skipping lesson process, then when I try to click on the skipping lesson button it says I am already skipping a lesson, btw I'm not clicking it when I'm on the lesson.

To Reproduce
Using the lesson skip button.

Expected Behavior
Pressing skipping lesson and it skips to the last question for me to answer.

Screenshots/Video

https://user-images.githubusercontent.com/90517061/153940895-fde51ca1-dc42-4faa-be6b-6321ebfe2fe5.mp4

**Comment by cupiditys** [comment]
idk how many times I have to tell you this but tf am I gonna do with a millimeter wide video???? it doesn’t need to be that small to cover ur name and obs is free

**Comment by n00b1017** [comment]
The screen is so wide that i can see the whole world

**Comment by cupiditys** [comment]
the problem is ur clicking skip lesson again, ur supposed to just open it
