### ISSUE TITLE
Opens once then closes permanently

### ISSUE THREAD

**Issue by SnailKale** [cupiditys/iReady-Overload#207]
The first time i used this it worked perfectly, but the next day (today) it decided it will open for less then a second and then disappear permanently.
**Expected Behavior**
for it to work
**Screenshot(s)/Video**
don't have any
**Additional info**
don't have any

**Comment by wengfuynetg** [comment]
same

**Comment by navoman123** [comment]
same

**Comment by cupiditys** [comment]
updated
