### ISSUE TITLE
[BUG] When i press skip lesson and go through the process it does not slowly go to the end like it should do

### ISSUE THREAD

**Issue by masssydoosy** [cupiditys/iReady-Overload#209]
help me im injured

**Comment by JustCallMeNathan** [comment]
same thing is happening for me

**Comment by emmanuel1644** [comment]
the skipper works for the math one but doesnt work for reading

**Comment by cupiditys** [comment]
yea they patched bruhh should have update later today if not tommorow

**Comment by Titanic-byte** [comment]
same is happening with me but with both >:(

**Comment by S2KJKP** [comment]
It says skipping lesson but doesnt skip

**Comment by IAMTHEONETHINGINLIFEICANCONTROL** [comment]
what a legend, literally at programming war with curriculum associates. I can't do too much programming, but you're like an inspiration. one of the nicest things I've seen from a individual. keep doing what you're doing man :D

**Comment by wengfuynetg** [comment]
> yea they patched bruhh should have update later today if not tommorow thanks for the update coming out the overload really helps

**Comment by cupiditys** [comment]
updated
