### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Titanic-byte** [cupiditys/iReady-Overload#210]
**Describe the bug** Whenever i try to skip Lesson it does not skip it it just does not move or anything like a normal lesson that you have to do it yourself

**To Reproduce**

**Expected behavior** its supposed to skip lesson 

**Screenshot(s)/Video**

**Additional info**

**Comment by cupiditys** [comment]
https://github.com/cupiditys/iReady-Overload/issues/209#issuecomment-1050363531

**Comment by cupiditys** [comment]
updated
