### ISSUE TITLE
Support for newer lessons

### ISSUE THREAD

**Issue by PlaugeMan** [cupiditys/iReady-Overload#214]
**Describe the feature**
Should update the script since I-ready released a different type of lesson a while back and doesn't work with lesson skipper
**Additional context**

**Comment by cupiditys** [comment]
wdym

**Comment by masssydoosy** [comment]
i think he means the math lessons like the classic G.O azul and jake like those lessons not sure exactly what lessons dude talking about but this seems like the same lesson cause its a little confusing to skip

**Comment by cupiditys** [comment]
it already has support for those
