### ISSUE TITLE
lesson skip not working

### ISSUE THREAD

**Issue by n00b1017** [cupiditys/iReady-Overload#216]
not skipping lessons

![image](https://user-images.githubusercontent.com/94810174/155775759-f1c3022b-cd3b-4954-b4c4-2113e406c7df.png)

**Comment by cupiditys** [comment]
i am aware

**Comment by n00b1017** [comment]
ok

**Comment by sightondrugs** [comment]
when is it going to be fixed cupiditys?

**Comment by cupiditys** [comment]
updated
