### ISSUE TITLE
[bug...]

### ISSUE THREAD

**Issue by LightRuby** [cupiditys/iReady-Overload#217]
So umm, the bug is everytime I open it, it disappears. I'm not sure if thats supposed to happen? But then I cant use it at all so please fix that.

**Comment by JordanMcshane23** [comment]
Did you update the newest version?

**Comment by cupiditys** [comment]
i am aware

**Comment by LightRuby** [comment]
> i am aware
Do you know I can fit it?

**Comment by LightRuby** [comment]
> Did you update the newest version?

Do I know you irl?

**Comment by navoman123** [comment]
> i am aware

is your name simon irl by any change?

**Comment by LightRuby** [comment]
> > i am aware
> 
> is your name simon irl by any change?

nope. sry.

**Comment by navoman123** [comment]
> > > i am aware
> > 
> > 
> > is your name simon irl by any change?
> 
> nope. sry.

sorry i ment the person who created this hack

**Comment by navoman123** [comment]
> i am aware

is your name simon irl by any chance?

**Comment by cupiditys** [comment]
> > i am aware
> 
> is your name simon irl by any chance?

what no
