### ISSUE TITLE
Skip lesson doesn't work

### ISSUE THREAD

**Issue by AvetomicBomb** [cupiditys/iReady-Overload#219]
Whenever I click the skip lesson button, it says "You may need to farm minutes" like usual, I click OK and it does it's thing, it shuts me out of the lesson twice like normal, but when I go back into the lesson for the third time it doesn't work. My I-ready is due sunday  (╥_╥)

**Comment by wengfuynetg** [comment]
they patched it but cupidity is gonna release it soon.

**Comment by cupiditys** [comment]
updated
