### ISSUE TITLE
yo cupid

### ISSUE THREAD

**Issue by AutoBotProject** [cupiditys/iReady-Overload#222]
I heared what you did to HypnoticLOL and could u do that again to someone else

**Comment by AutoBotProject** [comment]
my discord: ImABot#7520

**Comment by cupiditys** [comment]
depends who and what they did

**Comment by AutoBotProject** [comment]
I said it on the discord

**Comment by Supamariobros** [comment]
what did he do to hypnotic im really curious

**Comment by AutoBotProject** [comment]
dox.
