### ISSUE TITLE
Why is the quiz skipping not working :([BUG]

### ISSUE THREAD

**Issue by navoman123** [cupiditys/iReady-Overload#226]
the quiz skipping isn't working

**To Reproduce**

the quiz skipping should work

**Screenshot(s)/Video**

**Additional info**

**Comment by illusionTBA** [comment]
quiz is not working bcs it got patched he said it will be back up on monday

**Comment by navoman123** [comment]
> quiz is not working bcs it got patched he said it will be back up on monday

alr ty
