### ISSUE TITLE
for a different school product

### ISSUE THREAD

**Issue by X2isme** [cupiditys/iReady-Overload#227]
So I have to use this platform for school its called RSM, it rlly sucks, I can send you my login info to cupiditysxd@gmail.com
if you cant find a hack for it, I would really appreciate it.

**Comment by poopyhead121** [comment]
i dont know what that is...

**Comment by comradeduck** [comment]
Nice pfp

**Comment by X2isme** [comment]
> i dont know what that is...

who asked?

**Comment by X2isme** [comment]
> Nice pfp

Breh

**Comment by X2isme** [comment]
Im waiting

**Comment by comradeduck** [comment]
Do you have any screenshots to make me understand rsm?

**Comment by X2isme** [comment]
> Do you have any screenshots to make me understand rsm?

https://www.awesomescreenshot.com/image/23527392?key=25ab3c683eb32b47fa4a3fce50c38b0b

**Comment by comradeduck** [comment]
Never tried it

**Comment by cupiditys** [comment]
ngl i looked and i dont think it's possible sorry
