### ISSUE TITLE
it keep's crashing

### ISSUE THREAD

**Issue by cyber1109** [cupiditys/iReady-Overload#23]

**Comment by cupiditys** [comment]
u gotta tell me more than that

**Comment by cyber1109** [comment]
yes

**Comment by cyber1109** [comment]
ok so when i run it sometimes it will work but some times it will put me in a loading screen and wont work

**Comment by cupiditys** [comment]
send a picture of loading screen

**Comment by cyber1109** [comment]
cant diagnostic dose the hack work for diagnostic?

**Comment by Barnac1ed** [comment]
> ok so when i run it sometimes it will work but some times it will put me in a loading screen and wont work

happened to me, just reload the tab and try it again.

**Comment by n00b1017** [comment]
@Barnac1ed 
ye it just crashes again tho

**Comment by Barnac1ed** [comment]
> @Barnac1ed ye it just crashes again tho

then just exit iready tab entirely
