### ISSUE TITLE
lesson skipper currently unavaliable for quizzes

### ISSUE THREAD

**Issue by fasttypherintheworl** [cupiditys/iReady-Overload#230]
can you fix this please because it will not let me skip the quizzes no more

**Comment by illusionTBA** [comment]
he said he'll work on it when he feels like it

**Comment by user12345678909876543212345712387236** [comment]
thank you do you know when hes going to be done?

**Comment by illusionTBA** [comment]
nope. unsure if he has even started it :/

**Comment by user12345678909876543212345712387236** [comment]
damn, i dont want to do iready

**Comment by robodmanx** [comment]
you can manage for a singular week while it gets fixed

**Comment by CodeSalvageON** [comment]
https://vault0.netlify.app, small fix for diagnostic hack and quiz. Obv not instantaneous at all but it'll get you the right answer

**Comment by cupiditys** [comment]
> you can manage for a singular week while it gets fixed

ong its not gonna kill you

**Comment by comradeduck** [comment]
Rip my steak but really i don't care

**Comment by cupiditys** [comment]
done
