### ISSUE TITLE
quiz fix date?

### ISSUE THREAD

**Issue by paper1991** [cupiditys/iReady-Overload#231]
hey, no intent to pressure you are anything, but just wondering when will the quiz skipper work again? my teacher is really mad at me for not doing I ready and they are due the end of this week. thanks

**Comment by illusionTBA** [comment]
he said he will do it when he feels like it

**Comment by Tyleralexander120** [comment]
> hey, no intent to pressure you are anything, but just wondering when will the quiz skipper work again? my teacher is really mad at me for not doing I ready and they are due the end of this week. thanks

Bro it's not that hard just do the iready lessons legit instead of waiting so that your teacher won't be mad
