### ISSUE TITLE
when is ArjhanToteck going to update it?

### ISSUE THREAD

**Issue by windows95isgood** [cupiditys/iReady-Overload#235]
when is ArjhanToteck going to update it?

**Comment by cupiditys** [comment]
we dont talk about arjhantoteck around here

**Comment by windows95isgood** [comment]
but arjhantoteck is still doing all the work for the hack.

**Comment by cupiditys** [comment]
since when

**Comment by windows95isgood** [comment]
don't know why you deleted the messages :/

**Comment by cupiditys** [comment]
basically arjhan is completely lying, he helped with 1 update recently and only because he offered. i've completely rewrote everything from his original one and the only thing i have kept is ui because it doesn't matter

**Comment by cupiditys** [comment]
hes throwing a hissy fit for no reason

**Comment by windows95isgood** [comment]
oh is that y lesson skipper is in beta now ? mb

**Comment by CodeSalvageON** [comment]
Made the repo comply with GNU from ArjhanToteck's original repo, so @cupiditys check pull requests
