### ISSUE TITLE
[FEATURE] Add lesson auto completer script that automatically farms 30 minutes then completes lesson and quiz then repeats it over and over until its stopped

### ISSUE THREAD

**Issue by epicgamer3819** [cupiditys/iReady-Overload#238]
iready overload feature request

**Comment by TheOffZX** [comment]
Yo that could be nice, but I think it would be too time consuming because some teachers (like mine) dont check how much time you have spent, and it would be suspicious seeing exactly 30 minutes on a lesson every time. No more, no less.

**Comment by epicgamer3819** [comment]
> Yo that could be nice, but I think it would be too time consuming because some teachers (like mine) dont check how much time you have spent, and it would be suspicious seeing exactly 30 minutes on a lesson every time. No more, no less.

They can make it randomized, since its all in javascript, they can set the amount of time to around 20 minutes to 60 minutes max. It's not that hard to understnad

**Comment by cupiditys** [comment]
don't really see why
