### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by JustKhazi** [cupiditys/iReady-Overload#24]
<img width="454" alt="Screen Shot 2021-11-29 at 9 40 27 PM" src="https://user-images.githubusercontent.com/88862889/143976104-f27233d8-d132-4ff8-bb89-fec482a4d226.png">

I keep getting correct answers but it doesnt work

**Comment by cupiditys** [comment]
can you send a video?

**Comment by Barnac1ed** [comment]
> I keep getting correct answers but it doesnt work

you have to get the ENTIRE question correct, until it shows the green arrow. then you have to click the arrow and then skip the lesson.
