### ISSUE TITLE
[FEATURE] keybind for mac

### ISSUE THREAD

**Issue by urgay20** [cupiditys/iReady-Overload#243]
please add a keybind to hide the menu
🥲

**Comment by flowingss** [comment]
ctrl + z works on mac too, it just doesn't work sometimes when you are inside a lesson, otherwise when outside you can do ctrl + z. Also, you can just move the panel underneath where it will create a blank space with the panel so you can scroll to it.

**Comment by urgay20** [comment]
> ctrl + z works on mac too, it just doesn't work sometimes when you are inside a lesson, otherwise when outside you can do ctrl + z. Also, you can just move the panel underneath where it will create a blank space with the panel so you can scroll to it.

thanks found out the scroll thing but ctrl z just doesnt work idk why :/

**Comment by cupiditys** [comment]
doesn't usually work in lessons
