### ISSUE TITLE
QUIZ BUG

### ISSUE THREAD

**Issue by Gam3rrXD** [cupiditys/iReady-Overload#245]
I am always getting 83% on my quizzes, please fix the bug when ur free
![Screenshot_91](https://user-images.githubusercontent.com/84348006/156436139-fe81a89c-6476-44dd-8bdc-8049b8ccc1ec.png)

**Comment by NinTheCoolGuy** [comment]
![image](https://user-images.githubusercontent.com/90517061/156443671-06b25952-f4b2-4eed-901c-83bb24b246f5.png)

**Comment by cupiditys** [comment]
fixed in latest
