### ISSUE TITLE
Diagnostic Hack

### ISSUE THREAD

**Issue by DaniilnoIready** [cupiditys/iReady-Overload#246]
Sorry, but when you have the time, what does the diagnostic hack do?

**Comment by flowingss** [comment]
It skips lessons, farms minutes, and has a diagnostic hack which may work on some diagnostics but not all

**Comment by comradeduck** [comment]
Why hack in the diagnostic bro

**Comment by cupiditys** [comment]
diagnostic hack probably not possible
