### ISSUE TITLE
Doesn't score 100 on the quiz..

### ISSUE THREAD

**Issue by WhosHappyFox** [cupiditys/iReady-Overload#25]
Hey broski the bot doesnt get 100 on the quiz :/

**Comment by cupiditys** [comment]
i just tried and it worked for me, maybe you are doing something wrong?

**Comment by WhosHappyFox** [comment]
u got discord or snap??

**Comment by cupiditys** [comment]
cupiditys#2113

**Comment by Barnac1ed** [comment]
> Hey broski the bot doesnt get 100 on the quiz :/

did you already get a question incorrect before you ran the skipper?
