### ISSUE TITLE
[BUG] ALWAYS 100% LOOKIN TOO RISKY RN 

### ISSUE THREAD

**Issue by doxxedyou** [cupiditys/iReady-Overload#252]
it wont let me choose the % i want for it atm 

![image](https://user-images.githubusercontent.com/96793565/156665796-6322c371-3b52-4fef-86f2-53876abdb9cd.png)

**Comment by comradeduck** [comment]
Sorry but how the fuck did you get 100

**Comment by OnlyRail** [comment]
kid he used the hack are you dumb

**Comment by cupiditys** [comment]
better than getting a 0

**Comment by comradeduck** [comment]
> kid he used the hack are you dumb

Bro I know I meant when I used the hack it gave my 83 and shit bro
