### ISSUE TITLE
Client sided gui

### ISSUE THREAD

**Issue by comradeduck** [cupiditys/iReady-Overload#253]
Can you make it client sided?

**Comment by cupiditys** [comment]
what does this mean

**Comment by comradeduck** [comment]
Explaining what it means client sided pretty much means others can't see it but the user using it can

**Comment by HypnoticLOL** [comment]
> Explaining what it means client sided pretty much means others can't see it but the user using it can

it is, it dosnt show on other iready users computers unless there using it, if you mean not shown on like gogardian, thats not possible unless cupid makes a popup.html for the exstenion and you use that, but thats not going to happen given that cupid only dose things that can be used on both exstenion and bookmarklet.
