### ISSUE TITLE
[BUG] For some reason for I-Ready math, it mainly gives me a 100% but on I-Ready reading, it varies wildly

### ISSUE THREAD

**Issue by justincodingprojects** [cupiditys/iReady-Overload#255]
**Describe the bug**
Math: mainly 100%
Reading: Mine varies from 33% to 96% ._.
**To Reproduce**
Skip a lesson in both math and reading tabs and notice the slight difference
**Expected behavior**
Probably 100% on both but would like to see the ability to choose what score I want.
**Screenshot(s)/Video**
N/A (don't need to)
**Additional info**

**Comment by cupiditys** [comment]
done
