### ISSUE TITLE
[BUG] Finishing Lessons

### ISSUE THREAD

**Issue by qbfdesgfkdsAfjklgskl** [cupiditys/iReady-Overload#258]
The extension is no longer supplying fresh ass every time I rub the finish lesson button and it is very irritating. I ask you fix the ASAP.

**Comment by cupiditys** [comment]
wtf does this even mean

**Comment by qbfdesgfkdsAfjklgskl** [comment]
It no longer is supplying it, could you please fix it?

**Comment by cupiditys** [comment]
please explain

**Comment by qbfdesgfkdsAfjklgskl** [comment]
Please?

**Comment by qbfdesgfkdsAfjklgskl** [comment]
What could you possibly mean? I have already explained to you.

**Comment by cupiditys** [comment]
s

**Comment by qbfdesgfkdsAfjklgskl** [comment]
Just fix the button that shows fresssh ass when you finish the lesson. I need more.

**Comment by cupiditys** [comment]
it should already be producing enough ass

**Comment by qbfdesgfkdsAfjklgskl** [comment]
Fix it, it's not fresh nor does it do it anymore. I need the ability to rub it.

**Comment by dtactx12** [comment]
ok
