### ISSUE TITLE
check lesson

### ISSUE THREAD

**Issue by shanereportsissues** [cupiditys/iReady-Overload#260]
can you add a lesson skipper for checks? these things

**Additional context**

![Screenshot 2022-03-04 9 05 48 AM](https://user-images.githubusercontent.com/97711014/156777586-c6e568be-a0fc-48cb-8025-24628bcd70a6.png)
)

**Comment by cupiditys** [comment]
no clue what those are

**Comment by comradeduck** [comment]
Have you tried even skipping it if not then idk I usually get teacher assigned but not checks

**Comment by cupiditys** [comment]
i mean you can try with the skipper now it might work
