### ISSUE TITLE
Trying to make a custom wallpaper maker but.

### ISSUE THREAD

**Issue by comradeduck** [cupiditys/iReady-Overload#263]
What code does Iready use?

**Comment by HypnoticLOL** [comment]
yo I got that alr done on my github for cReady u can get the code there or its 
```document.getElementById("background-image").src='LINK_TO_IMAGE';

**Comment by SharkiArthur** [comment]
dont give out custom shit bro

**Comment by epicgamer2953** [comment]
nice

**Comment by X2isme** [comment]
make a bookmark and set the URL to this:   

javascript:(function()%7Bvar%20LINK%20%3D%20prompt(%22Image%20Link%22)%0Adocument.getElementById(%22background-image%22).src%3DLINK%3B%0Aalert(%22Image%20Set%22)%7D)()%3B

**Comment by comradeduck** [comment]
Thank you

**Comment by HypnoticLOL** [comment]
> dont give out custom shit bro

bro yk its open source?
