### ISSUE TITLE
Complicated.

### ISSUE THREAD

**Issue by masssydoosy** [cupiditys/iReady-Overload#27]
the non-extension way is too complicated because when i CTRL+SHIFT+I Opens Inspect I go to network All i see is my Roblox cookie. and a ping meter that's it can i get some help?

**Comment by cupiditys** [comment]
then use the extension way

**Comment by masssydoosy** [comment]
the Extension does not work like you said

**Comment by cupiditys** [comment]
it works now i updated it

u just have to download the newest version

**Comment by masssydoosy** [comment]
OMG THANK GOODNESS YOUR A LITERAL LIFE SAVER
also can i get the download link

**Comment by cupiditys** [comment]
https://github.com/cupiditys/iReady-Overload/blob/main/chromeExtension.zip?raw=true

**Comment by masssydoosy** [comment]
thx

**Comment by masssydoosy** [comment]
got an issue with newest version

**Comment by masssydoosy** [comment]
When i activate the LESSON SKIPPER

**Comment by masssydoosy** [comment]
and i get one question correct it goes Blank and it gets stuck on 3 blue dots and like a loading screen but it never loads

**Comment by masssydoosy** [comment]
help plz

**Comment by cupiditys** [comment]
reload page and try again

**Comment by masssydoosy** [comment]
i tried that

**Comment by masssydoosy** [comment]
got stuck again

**Comment by cupiditys** [comment]
when does it get stuck

**Comment by masssydoosy** [comment]
every time i click the lesson skipper button and get a question Correct it gets stuck every time

**Comment by cupiditys** [comment]
press ctrl shift i and go to the console tab and tell me what it says when u answer question

**Comment by masssydoosy** [comment]
Ok

**Comment by masssydoosy** [comment]
this is what it brings up pretty long :::::: app-vendor.chunk.js:2 
        
       appLogger :: [Dashboard User-Facing Error] API Error - url: undefined, data: {"errorCode":-9998,"httpStatus":0,"data":null,"gatewayError":true}
[User Agent] Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.34
[Chrome Platform] Platform: Windows Platform Version: 10.0.0 UA Full Version: 96.0.1054.34
[Route] /student/ActivityLaunchPage
[Store] {"student":{"id":"8a5480e07ac84231017b5d0e23ff02ad","districtId":"F4C5E8F9F4AB20490B7B8395815F56E6","stateId":"FL","gradeLevelData":{"id":"8a5480e07ac84231017b5d0e23ff02af","chronologicalGradeLevel":{"id":"6","name":"Grade 6","shortName":"6","orderIndex":6},"mathDevelopmentalLevel":{"id":null,"name":null,"shortName":null,"orderIndex":null},"elaDevelopmentalLevel":{"id":null,"name":null,"shortName":null,"orderIndex":null}},"primarySchoolEnrollment":{"id":"8a5480e07ac84231017b5d0e23ff02b0","school":{"id":"8a5482a87ac8362e017af829fc7f3946","name":"RCSA - Middle/High","enableSpanishDiagnostic":false,"enableSpanishFFA":false,"mdrId":null},"userId":"8a5480e07ac84231017b5d0e23ff02ad","schoolGroupId":null},"assessmentLanguage":"EN","studentGroupEnrollments":[{"id":"8a5480ce7ac84157017b5d0e246b16ef","studentId":"8a5480e07ac84231017b5d0e23ff02ad","studentGroupId":"8a5481697ac83109017b5b1abc7e6511","studentGroupType":"CLASS"},{"id":"8a5480ce7ac84157017b5d0e247d16f1","studentId":"8a5480e07ac84231017b5d0e23ff02ad","studentGroupId":"8a5482a87ac8362e017b5b1abc7d2639","studentGroupType":"CLASS"},{"id":"8a5480ce7ac84157017b5d0e24e81700","studentId":"8a5480e07ac84231017b5d0e23ff02ad","studentGroupId":"8a54816f7ac842ca017b5b1abc8f4957","studentGroupType":"CLASS"},{"id":"8a5480ce7ac84157017b5d0e24da16fe","studentId":"8a5480e07ac84231017b5d0e23ff02ad","studentGroupId":"8a5482a87ac8362e017b5b1abc7b2636","studentGroupType":"CLASS"},{"id":"8a5480ce7ac84157017b5d0e24ad16f7","studentId":"8a5480e07ac84231017b5d0e23ff02ad","studentGroupId":"8a54821e7ac8412f017b0a3516d23a96","studentGroupType":"CLASS"},{"id":"8a5480ce7ac84157017b5d0e248d16f3","studentId":"8a5480e07ac84231017b5d0e23ff02ad","studentGroupId":"8a5480167ac8448f017b5b1abc6c6069","studentGroupType":"CLASS"},{"id":"8a5480ce7ac84157017b5d0e249c16f4","studentId":"8a5480e07ac84231017b5d0e23ff02ad","studentGroupId":"8a5482a87ac8362e017b5b1abc9b2645","studentGroupType":"CLASS"},{"id":"8a5480ce7ac84157017b5d0e24ca16fc","studentId":"8a5480e07ac84231017b5d0e23ff02ad","studentGroupId":"8a5480e07ac84231017b5b1abc667ac7","studentGroupType":"CLASS"},{"id":"8a5480ce7ac84157017b5d0e24bd16fa","studentId":"8a5480e07ac84231017b5d0e23ff02ad","studentGroupId":"8a5481cb7ac843a0017b5b1abcbc464c","studentGroupType":"CLASS"}],"theme":{"id":"7fb11e488dea11e98b723be4c4298212","themeName":"Background_02","themePath":"Background_02","themeType":"HTML5_NON_TILEABLE"},"buddy":{"name":"Snargg"}},"selectedSubject":"ela","selectedTab":"TO_DO","lessonActivity":{"id":"45c8f594-8306-417c-8985-56e61f3d067c","dueDate":null,"today":null,"entityType":"lessonActivity","studentId":"8a5480e07ac84231017b5d0e23ff02ad","status":"IN_PROGRESS","lesson":{"id":"DI.ELA.COM.4.1008","name":"Describing Settings and Events","subject":"ela","gradeLevel":{"id":"4","name":"Grade 4","shortName":"4","orderIndex":4},"schoolYearLevel":{"id":"0","name":"Early","orderIndex":2,"placementLevel":true},"objectiveText":"<ul><li>Identify details in a story that relate to the setting and events.</li><li>Read and understand adventure stories.</li></ul>","channel":"MAIN","lessonType":"HTML_LESSON","orderIndex":4269,"estimatedSeconds":1500,"active":true,"track":{"id":"DI.ELA.COM","name":"Comprehension","orderIndex":4,"subject":"ela","associatedDiagnosticTrackId":"DI.ELA.COM","closeReadingTrack":false,"basalPracticeTrack":false},"languageType":"EN","tags":[{"id":"FOCUS_LESSONS","displayName":"Focus Lessons","description":""}]},"previouslyFailedActivityId":null,"componentActivities":[{"id":"DI.ELA.COM.4.1008.10_45c8f594-8306-417c-8985-56e61f3d067c_M_ela","entityType":"lessonComponentActivity","lessonActivity":null,"lessonComponent":{"id":"DI.ELA.COM.4.1008.10","componentType":"tutorial","contentFileName":"#/lesson/DI.ELA.COM.4.1008","contentDir":"/instruction/reading-comp/"},"status":"IN_PROGRESS"},{"id":"DI.ELA.COM.4.1008.20_45c8f594-8306-417c-8985-56e61f3d067c_M_ela","entityType":"lessonComponentActivity","lessonActivity":null,"lessonComponent":{"id":"DI.ELA.COM.4.1008.20","componentType":"quiz","contentFileName":"#/lesson/DI.ELA.COM.4.1008","contentDir":"/instruction/reading-comp/"},"status":"NOT_STARTED"}]},"selectedActivityType":"systemAssignedActivity","studentActivities":{"systemAssignedActivities":[{"entityType":"lessonActivity","status":"IN_PROGRESS","id":"DI.ELA.COM.4.1008","previouslyFailedActivityId":null,"channel":"MAIN","dueDate":null,"lessonType":"HTML_LESSON"}],"userAssignedActivities":[{"entityType":"lessonActivity","status":"IN_PROGRESS","id":"DI.ELA.COM.6.1034","previouslyFailedActivityId":null,"channel":"EXTRA_LESSON","dueDate":"12/03/21","lessonType":"HTML_LESSON"},{"entityType":"lessonActivity","status":"NOT_STARTED","id":"DI.ELA.COM.6.1035","previouslyFailedActivityId":null,"channel":"EXTRA_LESSON","dueDate":"12/03/21","lessonType":"HTML_LESSON"}],"userAssignedActivitiesPastDue":[]},"privileges":{"HAS_BROWSER_LOCKDOWN_ACCESS":false,"HAS_READING_SPANISH_FFA_ACCESS":false,"HAS_DIAGNOSTIC_SURVEY_ENABLED":true,"HAS_MY_STUFF_ACCESS":true,"HAS_GAME_ACCESS":true,"HAS_MATH_FLUENCY_ACCESS":false,"HAS_MATH_RC_SPANISH_ACCESS":false,"HAS_SHOW_DIAGNOSTIC_SCORE_ENABLED":true,"HAS_READING_INSTRUCTION_ACCESS":true,"HAS_MATH_READY_BOOK_LICENSE_CONSUMPTION":false,"HAS_MATH_BASAL_BOOK_CONTENT_ACCESS":false,"HAS_MATH_GROWTH_MONITORING_ACCESS":true,"HAS_MATH_READY_BOOK_ACCESS":false,"HAS_MATH_INSTRUCTION_ACCESS":true,"HAS_MATH_LEARNING_GAMES_LICENSE_CONSUMPTION":true,"HAS_READING_GROWTH_MONITORING_ACCESS":true,"HAS_READING_INSTRUCTION_LICENSE_CONSUMPTION":true,"HAS_READING_STANDARDS_MASTERY_ACCESS":true,"HAS_READING_DIAGNOSTIC_LICENSE_CONSUMPTION":true,"HAS_MATH_DIAGNOSTIC_ACCESS":true,"HAS_MATH_BASAL_PRACTICE_ACCESS":false,"HAS_READING_GROWTH_MONITORING_LICENSE_CONSUMPTION":false,"HAS_READING_STANDARDS_MASTERY_LICENSE_CONSUMPTION":false,"HAS_MATH_GROWTH_MONITORING_LICENSE_CONSUMPTION":false,"HAS_MATH_STANDARDS_MASTERY_ACCESS":true,"HAS_READING_DIAGNOSTIC_ACCESS":true,"HAS_MATH_BASAL_CHECK_ACCESS":false,"HAS_MATH_DIAGNOSTIC_LICENSE_CONSUMPTION":true,"HAS_MATH_INSTRUCTION_LICENSE_CONSUMPTION":true,"HAS_MATH_BASAL_CHECK_LICENSE_CONSUMPTION":false,"HAS_READING_SPANISH_FFA_LICENSE_CONSUMPTION":false,"HAS_MATH_STANDARDS_MASTERY_LICENSE_CONSUMPTION":false,"HAS_MATH_BASAL_BOOK_CONTENT_LICENSE_CONSUMPTION":false,"HAS_MATH_LEARNING_GAMES_ACCESS":true,"HAS_MATH_BASAL_PRACTICE_LICENSE_CONSUMPTION":false,"HAS_READING_ACCESS":true,"HAS_MATH_ACCESS":true,"HAS_BASAL_CHECK_MATH_SPANISH_ACCESS":false,"HAS_STANDARDS_MASTERY_MATH_SPANISH_ACCESS":false}}
[Stack] Error doesn't contain a message

**Comment by cupiditys** [comment]
try just completing the lesson normally and then trying again on next one

i think it's issue when you've already answered questions

**Comment by masssydoosy** [comment]
does it work with Comprehension lessons with (green) that does not include Bella Jake Sweet t and the other

**Comment by masssydoosy** [comment]
also should i get the question correct first and then click the button afterwards or click the button then correct

**Comment by jeandele124** [comment]
click the button first

**Comment by masssydoosy** [comment]
Ok so ive been doing it right

**Comment by jeandele124** [comment]
be careful using it on quizzes. i broke my iready using it

**Comment by masssydoosy** [comment]
was it permenant break

**Comment by jeandele124** [comment]
Yes. (well for me)

**Comment by jeandele124** [comment]
I literally cant login into math iready

**Comment by masssydoosy** [comment]
Ok so ill just use 2 devices for the quiz and just skip the instruction.

**Comment by jeandele124** [comment]
just dont exit out the quiz when the bar is full.

**Comment by masssydoosy** [comment]
k

**Comment by masssydoosy** [comment]
did not work with Math either

**Comment by jeandele124** [comment]
wait, what version you on? make sure ur on latest version

**Comment by masssydoosy** [comment]
Most recent

**Comment by masssydoosy** [comment]
I get one right and it the website goes black and has blue dots but wont load up

**Comment by jeandele124** [comment]
Get one right, then exit out the quiz, refresh and go back in and just keep clicking the arrow.

**Comment by masssydoosy** [comment]
im trying to skip the First part

**Comment by jeandele124** [comment]
alright ur problem. get help from  @cupiditys

**Comment by cupiditys** [comment]
> I get one right and it the website goes black and has blue dots but wont load up

it's supposed to go black, guess i should've made that more apparent
after it goes black refresh the page and keep opening and closing the lesson

**Comment by masssydoosy** [comment]
ok

**Comment by masssydoosy** [comment]
OMG IT WORKED!

**Comment by masssydoosy** [comment]
lets goooo

**Comment by cupiditys** [comment]
nice
