### ISSUE TITLE
Lesson skipper broke my I-ready

### ISSUE THREAD

**Issue by jeandele124** [cupiditys/iReady-Overload#28]
Hello, I broke my I-ready today while using the lesson skipper. I was following all instructions. I was on a quiz. The progress bar was filled up but it didn't end the quiz. So I exited out of it and went back in and now it keeps saying "Wait, something's wrong. Tap the green arrow button or ask your teacher for help." No matter how much I try, it won't go away. Worse thing is that I was using these hacks at school. Please fix this. @cupiditys

**Comment by cupiditys** [comment]
what type of lesson was it

**Comment by n00b1017** [comment]
you can fix it by redoing it, worked for me

**Comment by n00b1017** [comment]
like redoing the instructions

**Comment by n00b1017** [comment]
or does it show before you can even get into the lesson?

**Comment by jeandele124** [comment]
i cant get back on iready math

**Comment by jeandele124** [comment]
> what type of lesson was it

it was like dividing fractions with fractions idk

**Comment by jeandele124** [comment]
but i think the bug can happen any lesson

**Comment by n00b1017** [comment]
cupiditys can help you with that, idk how to code that well anyways

**Comment by jeandele124** [comment]
e

**Comment by cupiditys** [comment]
can you open inspect element and go to the network tab
and then try to open it
and then after right click on one of the names and click save all as fetch and send it

**Comment by jeandele124** [comment]
uhh sure

**Comment by jeandele124** [comment]
inspect element is blocked

**Comment by cupiditys** [comment]
dont know then

**Comment by jeandele124** [comment]
e

**Comment by jeandele124** [comment]
man i miss the other lesson skipper

**Comment by cupiditys** [comment]
its a "internal processing error" whenever iready tries to add the completed lesson to your account
its possible to kinda fix but not possible to prevent completely

**Comment by jeandele124** [comment]
so theres no way to fix it

**Comment by Barnac1ed** [comment]
Exit and reopen Iready
Happened to me did that and it works fine now so

**Comment by jeandele124** [comment]
> Exit and reopen Iready Happened to me and I did that and it works fine now so

I got a diagnostic now. But I tried that already.

**Comment by Quintinox** [comment]
I think I had the same problem, I'm not exactly sure though. But what I did was I put the original code in the console tab without switching all the falses to trues and without adding 1's. Again I'm not sure if your problem was the same as mine.

**Comment by REALDarianDev** [comment]
Hey everyone! I see you are having problems with I-Ready Hack. I can help with that. If you delete your cookies, Then reset your chrome history, it should work. If not do these steps:
Restart developer tools config. Then play around with your browsers, chrome is best. anything else might have issues.
Hacks arent really a big thing, just a piece of code that can bypass or trick the server. So sometimes it could be your I-Ready account. So playing around with your cookies and all will reset your login and using chrome is best for Bookmarklet and Extention.
