### ISSUE TITLE
scared to use it for diagnostic

### ISSUE THREAD

**Issue by Mrbobushie** [cupiditys/iReady-Overload#280]
I am scared because idk if its going to give me a really high score like 800 and all i want is like 600 or 650 and i dont trust it right now I have been trying to find a video on how it works and looks like also how much it gives you. So could you like make a youtube vid and give me a link or something plzzz? Thanks!

**Comment by qbfdesgfkdsAfjklgskl** [comment]
its normally random

**Comment by OnlyRail** [comment]
it doesnt work for all diagnostics and you shouldnt risk it bc if you get a 400 its gonna be an F if your teacher grades it

**Comment by cupiditys** [comment]
it doesnt even work
