### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by 2twenty-three3** [cupiditys/iReady-Overload#284]
its not working. when ever I skip a lesson it tells me to open the lesson again and its just staying its frozen. nothing has happened and when i click on it again it says that i am currently skipping a lesson.

**Comment by X2isme** [comment]
Are you going to the lesson and opening the lesson, then clicking "skip lesson" then exit the lesson and clicking the "skip lesson" button again?
I think thats how you do it, I'm not very sure.
