### ISSUE TITLE
[BUG] google search results error

### ISSUE THREAD

**Issue by epicgamer3819** [cupiditys/iReady-Overload#286]
**Describe the bug**
it says iready overload is the worst tool ever, by google
**To Reproduce**

**Expected behavior**
?
**Screenshot(s)/Video**

**Additional info**
![image](https://user-images.githubusercontent.com/100735364/158282101-0e29f0d4-8e8a-4181-be4f-67354b6f3f61.png)

**Comment by cupiditys** [comment]
fuck google
