### ISSUE TITLE
[FEATURE] Add trashready.xyz as a backup instance

### ISSUE THREAD

**Issue by yeeterlol** [cupiditys/iReady-Overload#287]
**Describe the feature**
On the Wiki, add trashready.xyz if cloudinary.com is blocked on the school filter or it goes randomly down.
**Additional context**

**Comment by illusionTBA** [comment]
or you can just copy and paste the code in the bookmarklet.txt into console or a bookmark

**Comment by cupiditys** [comment]
sorry nah im not adding any website thst i don't control, u could change the code to whatever you wanted
