### ISSUE TITLE
[Question] Blocked

### ISSUE THREAD

**Issue by TNT599** [cupiditys/iReady-Overload#294]
**Describe the bug**
Does not open when clicking the bookmarklet
**To Reproduce**
Click bookmark
**Expected behavior**
Should open menu
**Screenshot(s)/Video**
Will add later
**Additional info**

**Comment by firzm** [comment]
try your best to avoid bookmarks using the extension is way better

**Comment by TNT599** [comment]
I know, however my school account blocks extensions

**Comment by TNT599** [comment]
Yes, does it work for you?

**Comment by Barnac1ed** [comment]
> Yes, does it work for you?

mhm

**Comment by Ireadycoder** [comment]
google or your school is blocking bookmarks with the name "javascript:"

**Comment by Barnac1ed** [comment]
A fix I found was just typing javascript: and then pasting in the code into the url box and then pressing enter.

**Comment by TNT599** [comment]
Using the cloudinary link based one, it doesn't work, did cloudinary break?

**Comment by TNT599** [comment]
Just figured it out, school blocks javascript: bookmarks. Any way to fix?
