### ISSUE TITLE
do u think iready overload is gonna get patched soon?

### ISSUE THREAD

**Issue by epicgamer3819** [cupiditys/iReady-Overload#296]
**"iReady Connect" AND Teachers toolbox is going to be offline on the same day, as stated in** _"Two Upcoming i-Ready Maintenance Windows: 1. Thursday March 17th from 9:00pm to 11:00pm ET, Teacher Toolbox functionality will be unavailable; 2. From Sunday March 20th at 6:30am 9:30am ET, i-Ready will be offline for maintenance. We apologize for any inconvenience."_

**Comment by cupiditys** [comment]
sob
