### ISSUE TITLE
Huh? but I'm in a lesson!

### ISSUE THREAD

**Issue by jat354155** [cupiditys/iReady-Overload#299]
Unskippable lessons, painful.
Also you broke my non teacher assigned lesson
![Image](https://user-images.githubusercontent.com/91216411/159073194-8f05a8c0-b02e-4621-8776-9e7ddf1fbc15.png)
- (edit: how to reproduce bug, some lessons use an older format, something just doesn't detect those however)

**Comment by cupiditys** [comment]
close reading lessons are not supported

**Comment by jat354155** [comment]
Can the teachers see your inputs to the "-..." questions? If so I'm probably screwed. (Also my non teacher assigned lesson was skipped using the version that was here right after it came back up, is there any way to fix it without sounding sus to my ELA teacher?)

**Comment by cupiditys** [comment]
as long as u got minutes before it's fine
