### ISSUE TITLE
K this is an actual issue now lmao

### ISSUE THREAD

**Issue by n00b1017** [cupiditys/iReady-Overload#30]
Ye, so i used the lesson skipper and now it just, keeps me on a loading screen
[based on other issues]
![image](https://user-images.githubusercontent.com/94810174/144139847-31dbd422-3e34-4ac0-bbe7-de6a6ff50a97.png)

**Comment by n00b1017** [comment]
Just has me stuck with this

**Comment by jeandele124** [comment]
refresh page

**Comment by n00b1017** [comment]
yes ik how to do that, the point is to explain that the lesson skipper crashes ishitty

**Comment by Barnac1ed** [comment]
well there isn't another option, and we already knew this. you just refresh and try again. it may not be consistent, but it's still better than spending time on a lesson.

**Comment by cupiditys** [comment]
imma add a disclaimer whenever u use it that theres bugs and if something is wrong refresh

**Comment by n00b1017** [comment]
> well there isn't another option, and we already knew this. you just refresh and try again. it may not be consistent, but it's still better than spending time on a lesson.

ye ig thats true

**Comment by n00b1017** [comment]
would the loading screen mean that its doing its thing then

**Comment by n00b1017** [comment]
K i got it, u gotta click skip lesson and then leave lesson
![image](https://user-images.githubusercontent.com/94810174/144146206-72c2423b-57a2-4167-918b-54d303ee3b60.png)

**Comment by n00b1017** [comment]
@cupiditys u should probably put a tutorial on how to do it on the respitory (am bad at spelling)

**Comment by n00b1017** [comment]
last thing, wth is this bs
![image](https://user-images.githubusercontent.com/94810174/144146655-dc944a55-9e97-4868-8e54-6d82ef88a750.png)

**Comment by cupiditys** [comment]
u must of done something wrong

**Comment by n00b1017** [comment]
i didnt
