### ISSUE TITLE
[BUG]Can't hide the panel while in a lesson

### ISSUE THREAD

**Issue by insert-creative-name** [cupiditys/iReady-Overload#307]
When i'm in a lesson I can't close the panel

To Reproduce
press ctrl+z
Expected behavior
hide panel

**Comment by cupiditys** [comment]
u have to press ctrl and click this text
![image](https://user-images.githubusercontent.com/66990287/159371242-5ef2e074-c7ff-49be-8309-62fa7119e127.png)

**Comment by insert-creative-name** [comment]
it still doesn't work i also can't show it while i'm in a lesson
