### ISSUE TITLE
[BUG] Minute Hack Is patched

### ISSUE THREAD

**Issue by IreadyOverLoad** [cupiditys/iReady-Overload#313]
The Iready minute Hack is currently patched so don't go spamming in the comment "omg the iready minute hack is patched" leave the creator to do his job.

**Comment by Noahthao** [comment]
Go here to  make the min hack work https://github.com/mtocu/i-ready

**Comment by BetLokPlayz** [comment]
The minute hack is not patched, they just didn't "fix" it.

**Comment by NinTheCoolGuy** [comment]
> Go here to make the min hack work https://github.com/mtocu/i-ready

tell us how to use it then

**Comment by hattenwastaken** [comment]
try using version 0.1.14 while cupiditys comes out with the new update it isn't patched yet and the minutes hack and skipper work

**Comment by NinTheCoolGuy** [comment]
> try using version 0.1.14 while cupiditys comes out with the new update it isn't patched yet and the minutes hack and skipper work

they probably think it is patched because they cant get past 45 minutes or more
