### ISSUE TITLE
Diagnostic 

### ISSUE THREAD

**Issue by 8nine20** [cupiditys/iReady-Overload#32]
The Iready diagnostic script doesn't work I got a low ass score. when are you going to fix it? please try to if you can because Im going to retake it

**Comment by cupiditys** [comment]
i cant make it cuz i dont have a diagnostic test open

**Comment by 8nine20** [comment]
tough when do you have diagnostic test open?

**Comment by cupiditys** [comment]
idk probably not for months

**Comment by 8nine20** [comment]
if i gave u my login could u do it for me lol

**Comment by n00b1017** [comment]
![image](https://user-images.githubusercontent.com/94810174/144154514-8f7129aa-b055-4ca2-8450-8d06a31f5723.png)

**Comment by jeandele124** [comment]
lmao

**Comment by n00b1017** [comment]
Also i think they are doing another diagnostic soon because we are in like the middle of the second 9 weeks

**Comment by cupiditys** [comment]
> if i gave u my login could u do it for me lol

yea lol

**Comment by cyber1109** [comment]
i need it know im doing one

**Comment by cupiditys** [comment]
if you really want a new diagnostic hack someone with a diagnostic open has to give me their account sorry
