### ISSUE TITLE
Lesson skipper doesn't work :P

### ISSUE THREAD

**Issue by WhatHaveIGottenInto2020** [cupiditys/iReady-Overload#34]
The Lesson skipper don't work for me. I press the button, it says the text it normally says, and when I check the lesson to see if it was skipped, it didn't skip. I'm bad at coding but it said "usage.trackjs.com/usage.gif?token=7b0e187156f54c728faa8a4fd6cbceb5&correlationId=86469cc8-1124-42ca-9d1b-299e40eeb76f&application=math_prod&x=29991b08-ec8b-4476-a3a0-1a62d0e19377&:1 GET https://usage.trackjs.com/usage.gif?token=7b0e187156f54c728faa8a4fd6cbceb5&correlationId=86469cc8-1124-42ca-9d1b-299e40eeb76f&application=math_prod&x=29991b08-ec8b-4476-a3a0-1a62d0e19377& net::ERR_BLOCKED_BY_CLIENT" and "VM47:22 POST https://login.i-ready.com/student/lesson/componentCompleted 401"

Pls fix soon (when you have the time)

**Comment by WhatHaveIGottenInto2020** [comment]
Nvm I downloaded the new update

**Comment by WhatHaveIGottenInto2020** [comment]
How does skipper work??? it says get a right answer (I did get it right) but it doesn't skip to the quiz

**Comment by cupiditys** [comment]
> How does skipper work??? it says get a right answer (I did get it right) but it doesn't skip to the quiz

have you actually fully answered the question and the progress bar went up?

**Comment by cupiditys** [comment]
> The Lesson skipper don't work for me. I press the button, it says the text it normally says, and when I check the lesson to see if it was skipped, it didn't skip. I'm bad at coding but it said "usage.trackjs.com/usage.gif?token=7b0e187156f54c728faa8a4fd6cbceb5&correlationId=86469cc8-1124-42ca-9d1b-299e40eeb76f&application=math_prod&x=29991b08-ec8b-4476-a3a0-1a62d0e19377&:1 GET https://usage.trackjs.com/usage.gif?token=7b0e187156f54c728faa8a4fd6cbceb5&correlationId=86469cc8-1124-42ca-9d1b-299e40eeb76f&application=math_prod&x=29991b08-ec8b-4476-a3a0-1a62d0e19377& net::ERR_BLOCKED_BY_CLIENT" and "VM47:22 POST https://login.i-ready.com/student/lesson/componentCompleted 401"
> 
> Pls fix soon (when you have the time)

that has nothing to do with me

**Comment by WhatHaveIGottenInto2020** [comment]
Hey it works now (Sorry for the fuss)
