### ISSUE TITLE
iReady lesson skipper broke lesson

### ISSUE THREAD

**Issue by CentarCodes** [cupiditys/iReady-Overload#36]
It is stuck loading into the lesson. Here's console
![image](https://user-images.githubusercontent.com/93699371/144683096-6aa80582-2f06-4bb7-b1bd-7096e73b03bd.png)

**Comment by haloblaster** [comment]
just wait rn until he fixes the bugs or u might be able to use the extension

**Comment by cupiditys** [comment]
seems like more of a bug with iready, try pasting these files into the console when you have that text that says "CODE"

**Comment by cupiditys** [comment]
`// this will reset a lesson or quiz to its original state

// gets lesson data
var lessonId = html5Iframe.src.split("/")[html5Iframe.src.split("/").length - 1];
var csid = html5Iframe.src.split("?csid=")[1].split("&type")[0];
var lessonType = lessonId.split("_")[lessonId.split("_").length - 1];
var subject = csid.includes("math") ? "math" : "reading";

// empty global variables for later use
var slidesCompletedArr = [];
var scoreArr = [];
var slideCount;

// gets lesson strucure
html5Iframe.contentWindow.fetch(`https://cdn.i-ready.com/instruction/phoenix-content/${subject}/${lessonId}/lessonStructure.json`, {
		"headers": {
			"accept": "application/json, text/plain, */*",
			"accept-language": "en-US,en;q=0.9",
			"sec-fetch-dest": "empty",
			"sec-fetch-mode": "cors",
			"sec-fetch-site": "same-origin",
			"sec-gpc": "1"
		},
		"referrer": "https://login.i-ready.com/student/dashboard/home",
		"referrerPolicy": "strict-origin-when-cross-origin",
		"body": null,
		"method": "GET",
		"mode": "cors",
		"credentials": "include"
	}).then(response => response.json())
	.then(function(data) {
		console.log();
		slideCount = data.lessonStructureObj.slideData.length;

		slidesCompletedArr = [];
		scoreArr = [];

		// creates score and completion arrays with the length neccessary
		for (var i = 0; i < slideCount; i++) {
			slidesCompletedArr.push(false);
			scoreArr.push(1);
		}

		// sets cookies for external.js to use
		document.cookie = `lessonId=${lessonId};`
		document.cookie = `lessonType=${lessonType};`
		document.cookie = `subject=${subject};`
		document.cookie = `csid=${csid};`
		document.cookie = `slidesCompletedArr=${slidesCompletedArr};`
		document.cookie = `scoreArr=${scoreArr};`
		document.cookie = `slideCount=${slideCount};`
	});`

**Comment by cupiditys** [comment]
`// this will reset a lesson or quiz to its original state

// gets lesson data
var lessonId = html5Iframe.src.split("/")[html5Iframe.src.split("/").length - 1];
var csid = html5Iframe.src.split("?csid=")[1].split("&type")[0];
var lessonType = lessonId.split("_")[lessonId.split("_").length - 1];
var subject = csid.includes("math") ? "math" : "reading";

// empty global variables for later use
var slidesCompletedArr = [];
var scoreArr = [];
var slideCount;

// gets lesson strucure
html5Iframe.contentWindow.fetch(`https://cdn.i-ready.com/instruction/phoenix-content/${subject}/${lessonId}/lessonStructure.json`, {
		"headers": {
			"accept": "application/json, text/plain, */*",
			"accept-language": "en-US,en;q=0.9",
			"sec-fetch-dest": "empty",
			"sec-fetch-mode": "cors",
			"sec-fetch-site": "same-origin",
			"sec-gpc": "1"
		},
		"referrer": "https://login.i-ready.com/student/dashboard/home",
		"referrerPolicy": "strict-origin-when-cross-origin",
		"body": null,
		"method": "GET",
		"mode": "cors",
		"credentials": "include"
	}).then(response => response.json())
	.then(function(data) {
		console.log();
		slideCount = data.lessonStructureObj.slideData.length;

		slidesCompletedArr = [];
		scoreArr = [];

		// creates score and completion arrays with the length neccessary
		for (var i = 0; i < slideCount; i++) {
			slidesCompletedArr.push(false);
			scoreArr.push(1);
		}

		// sets cookies for external.js to use
		document.cookie = `lessonId=${lessonId};`
		document.cookie = `lessonType=${lessonType};`
		document.cookie = `subject=${subject};`
		document.cookie = `csid=${csid};`
		document.cookie = `slidesCompletedArr=${slidesCompletedArr};`
		document.cookie = `scoreArr=${scoreArr};`
		document.cookie = `slideCount=${slideCount};`
	});`

**Comment by cupiditys** [comment]
```// this will reset a lesson or quiz to its original state

// gets lesson data
var lessonId = html5Iframe.src.split("/")[html5Iframe.src.split("/").length - 1];
var csid = html5Iframe.src.split("?csid=")[1].split("&type")[0];
var lessonType = lessonId.split("_")[lessonId.split("_").length - 1];
var subject = csid.includes("math") ? "math" : "reading";

// empty global variables for later use
var slidesCompletedArr = [];
var scoreArr = [];
var slideCount;

// gets lesson strucure
html5Iframe.contentWindow.fetch(`https://cdn.i-ready.com/instruction/phoenix-content/${subject}/${lessonId}/lessonStructure.json`, {
		"headers": {
			"accept": "application/json, text/plain, */*",
			"accept-language": "en-US,en;q=0.9",
			"sec-fetch-dest": "empty",
			"sec-fetch-mode": "cors",
			"sec-fetch-site": "same-origin",
			"sec-gpc": "1"
		},
		"referrer": "https://login.i-ready.com/student/dashboard/home",
		"referrerPolicy": "strict-origin-when-cross-origin",
		"body": null,
		"method": "GET",
		"mode": "cors",
		"credentials": "include"
	}).then(response => response.json())
	.then(function(data) {
		console.log();
		slideCount = data.lessonStructureObj.slideData.length;

		slidesCompletedArr = [];
		scoreArr = [];

		// creates score and completion arrays with the length neccessary
		for (var i = 0; i < slideCount; i++) {
			slidesCompletedArr.push(false);
			scoreArr.push(1);
		}

		// sets cookies for external.js to use
		document.cookie = `lessonId=${lessonId};`
		document.cookie = `lessonType=${lessonType};`
		document.cookie = `subject=${subject};`
		document.cookie = `csid=${csid};`
		document.cookie = `slidesCompletedArr=${slidesCompletedArr};`
		document.cookie = `scoreArr=${scoreArr};`
		document.cookie = `slideCount=${slideCount};`
	});```

**Comment by cupiditys** [comment]
https://raw.githubusercontent.com/FailedWare/iReady-Overload-reuploaded/main/iReady-Overload-main/olderVersions/v1/resetLesson.js

**Comment by cupiditys** [comment]
https://raw.githubusercontent.com/FailedWare/iReady-Overload-reuploaded/main/iReady-Overload-main/olderVersions/v1/external.js

**Comment by cupiditys** [comment]
(you have to refresh the page and go onto the dashboard before pasting external.js)

**Comment by cupiditys** [comment]
im gonna assume youve fixed it
