### ISSUE TITLE
[BUG] FIX IREADY OVERLOAD

### ISSUE THREAD

**Issue by fortnite2022x** [cupiditys/iReady-Overload#376]
**Describe the feature**
Theres over 80+ active issue requests, most of them are about bugs.... WHY CANT U FIXXX ITTTT 😡😡
**Additional context**
FIX I READY OVERLOAD WE'RE MAD. IM NOT JOKING EITHER. ITS BEEN PATCHED FOR DAYS WITH NO FIX

**Comment by KillaNAdev** [comment]
Please Respectfully Be quiet. He is working on a fix. It will get done when it gets done.

**Comment by cupiditys** [comment]
people like you are the reason i dont want to update this anymore

**Comment by KillaNAdev** [comment]
> people like you are the reason i dont want to update this anymore

he makes me extremely mad for no reason

**Comment by fortnite2022x** [comment]
> > people like you are the reason i dont want to update this anymore
> 
> he makes me extremely mad for no reason

Oh wow. Sorry for wanting to skip iReady lessons with an extension that HE MADE PRIVATE so that it no longer works and wont release an update for. TOTALLYYYYY my fault. TOTALLY.
