### ISSUE TITLE
My info for a good diagnostic hack.

### ISSUE THREAD

**Issue by REALDarianDev** [cupiditys/iReady-Overload#38]
Hi @cupiditys. I will give you my info for a working diagnostic hack. My diagnostic is in 2 days.

**Comment by REALDarianDev** [comment]
Agree?

**Comment by cupiditys** [comment]
ok sure

**Comment by REALDarianDev** [comment]
Sure! Here is my User:
S20099394
Password:
D26m9394

**Comment by REALDarianDev** [comment]
The State is Florida

**Comment by REALDarianDev** [comment]
I'll email to you.

**Comment by REALDarianDev** [comment]
Done @cupiditys

**Comment by cupiditys** [comment]
ok what time does it open?

**Comment by REALDarianDev** [comment]
The math diognostic opens tuesday, in 2 days, and the readying starts in 1 week.

**Comment by cupiditys** [comment]
ok
