### ISSUE TITLE
The longer lessons (the old ones) dont seem to be compatible with the extention

### ISSUE THREAD

**Issue by PotatoGigabyte** [cupiditys/iReady-Overload#39]
when u click skip lesson it says to exit out of the lesson and go back, when i do and click skip again it just says "you are skipping a lesson already"

**Comment by cupiditys** [comment]
can you send a video

**Comment by PotatoGigabyte** [comment]
ill try sending it after i get out of school tomorrow bc rn its like 1 am

**Comment by n00b1017** [comment]
It worked for me

**Comment by n00b1017** [comment]
Maybe you are doing something wrong, try restarting your computer or reinstalling the extension.

**Comment by n00b1017** [comment]
also you should close this issue
