### ISSUE TITLE
lesson skipper getting a low reading score

### ISSUE THREAD

**Issue by n00b1017** [cupiditys/iReady-Overload#40]
I go on the quiz and get the first question right, use the lesson skipper, and then it gives me a 50%

**Comment by cupiditys** [comment]
are you getting the question at the end wrong

**Comment by Ireadycoder** [comment]
yea he did bc thats what it does, you have to get the first and last question right.

**Comment by n00b1017** [comment]
i get both right

**Comment by cupiditys** [comment]
likely story

**Comment by masssydoosy** [comment]
im so pissed i lost my 98 lesson steak cause of the quiz lesson skipper great now i lost my great streak :( should have been a warning

**Comment by masssydoosy** [comment]
F in the chat

**Comment by masssydoosy** [comment]
First ever lesson failed in years :( *because i had other smart ways of cheating to Multiple Devices and Close reading Correct answers from a device thing*

**Comment by cupiditys** [comment]
> im so pissed i lost my 98 lesson steak cause of the quiz lesson skipper great now i lost my great streak :( should have been a warning

shouldve waited like an hour im about to release a new one u can choose score

**Comment by masssydoosy** [comment]
wow im so unlucky XD

**Comment by cupiditys** [comment]
use new one
