### ISSUE TITLE
File won't be accepted into chrome extensions

### ISSUE THREAD

**Issue by eli249** [cupiditys/iReady-Overload#41]
I tried to drop file in chrome extensions and it won't take it.

**Comment by REALDarianDev** [comment]
DO you have Dev mode on?

**Comment by n00b1017** [comment]
No i had this same issue yesterday, it says the manifest file is missing

**Comment by cupiditys** [comment]
> No i had this same issue yesterday, it says the manifest file is missing

did you extract it
