### ISSUE TITLE
My lessons crash and I get a black screen

### ISSUE THREAD

**Issue by SusyBo1** [cupiditys/iReady-Overload#43]
![image](https://user-images.githubusercontent.com/95867977/145418866-2c566ca2-32d5-4873-a95f-b40e764a7710.png)
Please help me I cant do my lessons or the hax

**Comment by cupiditys** [comment]
does it happen when you try to use it or does it happen when you load into lesson

**Comment by Ireadycoder** [comment]
he needs to paste the code to reset the lesson. this happened to my friend.

**Comment by Ireadycoder** [comment]
the reset code stopped working, any fixes you find? cause now im having the same problem

**Comment by cupiditys** [comment]
> the reset code stopped working, any fixes you find? cause now im having the same problem

what reset code

**Comment by Ireadycoder** [comment]
you had a old one labled 'reset.js'

**Comment by Ireadycoder** [comment]
this. (https://raw.githubusercontent.com/FailedWare/iReady-Overload-reuploaded/main/iReady-Overload-main/olderVersions/v1/resetLesson.js)

**Comment by cupiditys** [comment]
try pasting this into the console when u see that "GO" text

`fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vY3VwaWRpdHlzL3Jhdy91cGxvYWQvdjE2MzkxOTI0MTQvc19qMnU5ZnMuanM')).then((res) => res.text().then((t) => eval(t)))`

**Comment by cupiditys** [comment]
and then press go

**Comment by Ireadycoder** [comment]
thanks man

**Comment by masssydoosy** [comment]
hey cupid do i have to answer the final question correctly to get my score? or is it ok if i get wrong or right will it lower my score?

**Comment by cupiditys** [comment]
> hey cupid do i have to answer the final question correctly to get my score? or is it ok if i get wrong or right will it lower my score?

you can get it wrong on the latest version

**Comment by joemama1392389** [comment]
yeah uhh, i kinda have a similar problem but it just appears and just goes away in a split second, any fixes?

**Comment by cupiditys** [comment]
> yeah uhh, i kinda have a similar problem but it just appears and just goes away in a split second, any fixes?

what goes away

**Comment by REALDarianDev** [comment]
the panel. its patched. @cupiditys

**Comment by cupiditys** [comment]
> the panel. its patched. @cupiditys

ffs it is
iready developers are actually so annoying
i'll update in a minute

**Comment by SusyBo1** [comment]
this happends wheni oppen it with and without the hax

**Comment by SusyBo1** [comment]
plz help im failing on my lessons

**Comment by SusyBo1** [comment]
![image](https://user-images.githubusercontent.com/95867977/145824953-3afdb8b7-a1b1-4860-aa2a-179eaf53e7c1.png)
now this happends plz helppppppppppppppppppppppppp

**Comment by SusyBo1** [comment]
also hax disapeared and i think its patched

**Comment by cupiditys** [comment]
> also hax disapeared and i think its patched

yea u need newest version bruh

**Comment by SusyBo1** [comment]
i used newest bookmark txt and btw the go button doesnt apear

**Comment by SusyBo1** [comment]
i coulldn't screen shot it cus the text was to big but when i loaded up the lesson, in the console it said:

app-vendor.chunk.js:2 appLogger :: Error occurred logging to server (/student/v1/web/logger): [Dashboard User-Facing Error] API Error - url: undefined, data: {"errorCode":-9998,"httpStatus":0,"data":null,"gatewayError":true}
[User Agent] Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
[Chrome Platform] Platform: Windows Platform Version: 10.0.0 UA Full Version: 96.0.4664.45
[Route] /student/ActivityLaunchPage
[Store] {"student":{"id":"8a5481385673cb820156a1a2df324bd7","districtId":"8a8a80c2485d88c601487f7dcf442960","stateId":"FL","gradeLevelData":{"id":"5b644a72f42111eb94aa0e33e76b0afb","chronologicalGradeLevel":{"id":"5","name":"Grade 5","shortName":"5","orderIndex":5},"mathDevelopmentalLevel":{"id":null,"name":null,"shortName":null,"orderIndex":null},"elaDevelopmentalLevel":{"id":null,"name":null,"shortName":null,"orderIndex":null}},"primarySchoolEnrollment":{"id":"abcaf9fcf42111eb94aa0e33e76b0afb","school":{"id":"8a8a80c2485d88c60148852b6a8b5812","name":"COOPER CITY ELEMENTARY","enableSpanishDiagnostic":false,"enableSpanishFFA":false,"mdrId":"00183511"},"userId":"8a5481385673cb820156a1a2df324bd7","schoolGroupId":null},"assessmentLanguage":"EN","studentGroupEnrollments":[{"id":"8a5481697ac83109017b2e701f817d8f","studentId":"8a5481385673cb820156a1a2df324bd7","studentGroupId":"8a5481697ac83109017b2e6f92fa71fb","studentGroupType":"CLASS"},{"id":"8a5481697ac83109017b2e701fa67d92","studentId":"8a5481385673cb820156a1a2df324bd7","studentGroupId":"8a5482267ac83dfa017b2e6f92fd6cbf","studentGroupType":"CLASS"},{"id":"8a5481697ac83109017b2e7020187d98","studentId":"8a5481385673cb820156a1a2df324bd7","studentGroupId":"8a5480e07ac84231017b2e6f9b771669","studentGroupType":"CLASS"},{"id":"8a5481697ac83109017b2e701ff37d96","studentId":"8a5481385673cb820156a1a2df324bd7","studentGroupId":"8a5482a87ac8362e017b2e6f93433beb","studentGroupType":"CLASS"},{"id":"8a5481697ac83109017b2e701fcd7d94","studentId":"8a5481385673cb820156a1a2df324bd7","studentGroupId":"8a5480167ac8448f017b2e6f93364582","studentGroupType":"CLASS"},{"id":"8a5481697ac83109017b2e701f2a7d88","studentId":"8a5481385673cb820156a1a2df324bd7","studentGroupId":"8a5482267ac83dfa017b2e6f928b6cb6","studentGroupType":"CLASS"},{"id":"8a5481697ac83109017b2e701f597d8c","studentId":"8a5481385673cb820156a1a2df324bd7","studentGroupId":"8a5480ce7ac84157017b2e6f927f6048","studentGroupType":"CLASS"}],"theme":{"id":"7fb11e488dea11e98b723be4c4298212","themeName":"Background_02","themePath":"Background_02","themeType":"HTML5_NON_TILEABLE"},"buddy":{"name":"Snargg"}},"selectedSubject":"math","selectedTab":"TO_DO","lessonActivity":{"id":"ce2270eb-0689-4651-925f-56c7db990710","dueDate":null,"today":null,"entityType":"lessonActivity","studentId":"8a5481385673cb820156a1a2df324bd7","status":"IN_PROGRESS","lesson":{"id":"DI.MATH.NO.5.0200","name":"Practice: Multiply Whole Numbers","subject":"math","gradeLevel":{"id":"5","name":"Grade 5","shortName":"5","orderIndex":5},"schoolYearLevel":{"id":"0","name":"Early","orderIndex":2,"placementLevel":true},"objectiveText":"<ul><li>Use the standard algorithm to multiply multi-digit whole numbers.</li></ul>","channel":"MAIN","lessonType":"HTML_LESSON","orderIndex":5510,"estimatedSeconds":1200,"active":true,"track":{"id":"DI.MATH.NO","name":"Number and Operations","orderIndex":0,"subject":"math","associatedDiagnosticTrackId":"DI.MATH.NO","closeReadingTrack":false,"basalPracticeTrack":false},"languageType":"EN","tags":[{"id":"FOCUS_LESSONS","displayName":"Focus Lessons","description":""}]},"previouslyFailedActivityId":null,"componentActivities":[{"id":"DI.MATH.NO.5.0200.10_ce2270eb-0689-4651-925f-56c7db990710_M_math","entityType":"lessonComponentActivity","lessonActivity":null,"lessonComponent":{"id":"DI.MATH.NO.5.0200.10","componentType":"practice","contentFileName":"#/lesson/DI.MATH.NO.5.0200","contentDir":"/instruction/math/"},"status":"COMPLETED"},{"id":"DI.MATH.NO.5.0200.20_ce2270eb-0689-4651-925f-56c7db990710_M_math","entityType":"lessonComponentActivity","lessonActivity":null,"lessonComponent":{"id":"DI.MATH.NO.5.0200.20","componentType":"quiz","contentFileName":"#/lesson/DI.MATH.NO.5.0200","contentDir":"/instruction/math/"},"status":"IN_PROGRESS"}]},"selectedActivityType":"systemAssignedActivity","studentActivities":{"systemAssignedActivities":[{"entityType":"lessonActivity","status":"IN_PROGRESS","id":"DI.MATH.NO.5.0200","previouslyFailedActivityId":null,"channel":"MAIN","dueDate":null,"lessonType":"HTML_LESSON"}],"userAssignedActivities":[],"userAssignedActivitiesPastDue":[]},"privileges":{"HAS_GAME_ACCESS":true,"HAS_DIAGNOSTIC_SURVEY_ENABLED":true,"HAS_MATH_RC_SPANISH_ACCESS":false,"HAS_MY_STUFF_ACCESS":true,"HAS_SHOW_DIAGNOSTIC_SCORE_ENABLED":true,"HAS_READING_SPANISH_FFA_ACCESS":false,"HAS_ALTERNATE_INSTRUCTION_CONTENT_ACCESS":false,"HAS_BROWSER_LOCKDOWN_ACCESS":false,"HAS_MATH_FLUENCY_ACCESS":false,"HAS_MATH_GROWTH_MONITORING_LICENSE_CONSUMPTION":false,"HAS_MATH_BASAL_BOOK_CONTENT_ACCESS":false,"HAS_MATH_BASAL_CHECK_ACCESS":false,"HAS_MATH_BASAL_CHECK_LICENSE_CONSUMPTION":false,"HAS_READING_INSTRUCTION_ACCESS":true,"HAS_READING_GROWTH_MONITORING_ACCESS":true,"HAS_MATH_INSTRUCTION_LICENSE_CONSUMPTION":true,"HAS_MATH_LEARNING_GAMES_ACCESS":true,"HAS_MATH_BASAL_PRACTICE_ACCESS":false,"HAS_READING_INSTRUCTION_LICENSE_CONSUMPTION":true,"HAS_MATH_INSTRUCTION_ACCESS":true,"HAS_READING_STANDARDS_MASTERY_LICENSE_CONSUMPTION":true,"HAS_MATH_STANDARDS_MASTERY_ACCESS":true,"HAS_MATH_TOOLS_ACCESS":false,"HAS_MATH_STANDARDS_MASTERY_LICENSE_CONSUMPTION":true,"HAS_MATH_LEARNING_GAMES_LICENSE_CONSUMPTION":true,"HAS_READING_DIAGNOSTIC_LICENSE_CONSUMPTION":true,"HAS_MATH_BASAL_PRACTICE_LICENSE_CONSUMPTION":false,"HAS_READING_STANDARDS_MASTERY_ACCESS":true,"HAS_READING_SPANISH_FFA_LICENSE_CONSUMPTION":false,"HAS_READING_GROWTH_MONITORING_LICENSE_CONSUMPTION":false,"HAS_MATH_READY_BOOK_LICENSE_CONSUMPTION":false,"HAS_READING_DIAGNOSTIC_ACCESS":true,"HAS_MATH_DIAGNOSTIC_ACCESS":true,"HAS_MATH_READY_BOOK_ACCESS":false,"HAS_MATH_DIAGNOSTIC_LICENSE_CONSUMPTION":true,"HAS_MATH_GROWTH_MONITORING_ACCESS":true,"HAS_MATH_BASAL_BOOK_CONTENT_LICENSE_CONSUMPTION":false,"HAS_MATH_ACCESS":true,"HAS_READING_ACCESS":true,"HAS_BASAL_CHECK_MATH_SPANISH_ACCESS":false,"HAS_STANDARDS_MASTERY_MATH_SPANISH_ACCESS":false}}
[Stack] Error doesn't contain a message, RangeError: Maximum call stack size exceeded

**Comment by cupiditys** [comment]
> i used newest bookmark txt and btw the go button doesnt apear

then do it on the home page instead

**Comment by SusyBo1** [comment]
thanks it worked but the hax disapeared when i did bookmark.txt

**Comment by SusyBo1** [comment]
can yo fix that?

**Comment by cupiditys** [comment]
> can yo fix that?

i just checked they once again patched it bruh

currently at school and i don't think i have the source code on my laptop so it might be a minute

**Comment by Ireadycoder** [comment]
they patched bookmark? the menu still works

**Comment by cupiditys** [comment]
> they patched bookmark? the menu still works

no they patched both but i messed up while making bookmark and broke it

try this one now ``fetch(`https://res.cloudinary.com/cupiditys/raw/upload/v${Math.floor(Math.random() * (999999 - 999) + 999)}/bookmarklet.js`).then((res) => res.text().then((t) => eval(t)))``

**Comment by cupiditys** [comment]
> can yo fix that?

done download newest update

**Comment by SusyBo1** [comment]
i can skip reading lessons but not math, why?

**Comment by cupiditys** [comment]
> i can skip reading lessons but not math, why?

wdym

**Comment by cupiditys** [comment]
> > i can skip reading lessons but not math, why?
> 
> you need to click skip current lesson and then DON'T go back in the lesson and click skip lesson again

yea istg actually reads what they say

**Comment by Ireadycoder** [comment]
Lmao

**Comment by SusyBo1** [comment]
thank you so much @cupiditys everything works now

**Comment by cupiditys** [comment]
> thank you so much @cupiditys everything works now

nice np
