### ISSUE TITLE
Just a question, not a issue

### ISSUE THREAD

**Issue by xelnu** [cupiditys/iReady-Overload#44]
Last time the Diagnostic hack didn't work, does it work now? I'm asking this because I saw that you updated it yesterday.

**Comment by cupiditys** [comment]
did you read what i changed

**Comment by woodycampbell** [comment]
i read but do not see a answer to the diagnosick problem, i see stuff in the bottom ab the "iready-overload" being banned but no diagnostic would u mind explaining if it works.

**Comment by cupiditys** [comment]
no it doesn't
