### ISSUE TITLE
Iready overload not working at all.

### ISSUE THREAD

**Issue by ghost** [cupiditys/iReady-Overload#46]
I log on today and my iready overload (yes, i pasted javascript:etc into the browser AND console.) and it just appeared and then poof, its gone in a split second. Iready is working on an update right now until 11:00AM so im just kinda like, yeah.. Anything i could do?

**Comment by joemama1392389** [comment]
sorry im screwing up my grammar im just tired lol

**Comment by REALDarianDev** [comment]
Bro, intsall new update, Thats becausse your using old one thats patched...

**Comment by REALDarianDev** [comment]
Oh wait nevermind, Its patched.

**Comment by REALDarianDev** [comment]
wait until cupiditys updates it.

**Comment by joemama1392389** [comment]
fuck.

**Comment by joemama1392389** [comment]
but wait, is it because it contains the words iready overload again?

**Comment by REALDarianDev** [comment]
No, he added a font to bypass that.

**Comment by masssydoosy** [comment]
ding dongs its not really patched you can easily quickly press the button everything works besides it shows up without getting removed.

**Comment by masssydoosy** [comment]
everything still works fine.

**Comment by REALDarianDev** [comment]
ding dong the ui wont load, thats called "patched" ding dong

**Comment by REALDarianDev** [comment]
bitch

**Comment by masssydoosy** [comment]
Check discord @REALDarianDev

**Comment by masssydoosy** [comment]
Check discord @REALDarianDev

**Comment by REALDarianDev** [comment]
WDYM? its all patched?

**Comment by REALDarianDev** [comment]
Huh?

**Comment by REALDarianDev** [comment]
Cant.

**Comment by masssydoosy** [comment]
i am actually watching drian

**Comment by REALDarianDev** [comment]
whos drian?

**Comment by masssydoosy** [comment]
deez nuts

**Comment by REALDarianDev** [comment]
Im doing homework and devoloping

**Comment by masssydoosy** [comment]
Hmmm your Azure server has been shut down cause your last name is [Privated]

**Comment by cupiditys** [comment]
updated
