### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by leeleedondon** [cupiditys/iReady-Overload#49]
I did the lesson skipper and it logged me out then said this
![Screenshot_50](https://user-images.githubusercontent.com/96024139/145728509-a9e54f52-539e-46aa-adaf-a6393767b02f.png)

**Comment by leeleedondon** [comment]
It happens as soon as I go on iready and I do not see any of the math or reading things at all

**Comment by cupiditys** [comment]
what version were you using?

**Comment by Barnac1ed** [comment]
damn wonder how they're gonna explain this to their teachers

**Comment by leeleedondon** [comment]
I was using 0.1.4 Javascript versions, I am still blocked

**Comment by cupiditys** [comment]
yea if u used 0.1.4 after it got patched and tried to skip lesson your account got blocked
im not sure who has the power to unblock accounts but if teachers do then it should be fairly easy to get it unblocked
if its higher up people then im not sure what to tell you sorry

**Comment by n00b1017** [comment]
poor guy lol
