### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by JuiceKidd** [cupiditys/iReady-Overload#52]
I think to stop i-ready developers from viewing the code to patch the menu you should (btw as I say at the bottom, I'm still thankful you made this and you don't have to do any of this I'd just think that'll save you time from having to patch this more and I also don't know much about discord bots so I kind of a lost cause to help you make a server)

1. Make a discord server that allows verification to stop them from viewing code freely, like having a verification bot that stops them from looking through channels and actually seeing anything. New accounts they make won't get passed easily since you can view their account creation date with bots like Dyno (I think)

2. Make this a private hack and handpick trusted people that can use it.

I dunno if you'll take my advice but I think having the code completely public for the I-Ready devs to see is kinda a problem
as they have patched it twice and have been enforcing their terms of use as an account has been blocked already and all of the people who use I-Ready are students and having an account blocked is kinda on them but having it patched is the cause of it being public. Don't take this the wrong way and you don't even need to follow this since your keeping it alive and I'm thankful for you saving me from boring-ass lessons that suck ass.

**Comment by cupiditys** [comment]
the code is obfuscated and i just dont want to handpick sorry

**Comment by Auzgame** [comment]
> the code is obfuscated and i just dont want to handpick sorry

Hey I've actually was able to deobfuscate your code (no offence), and I'm a intermediete when it comes to coding/reading js/html/css so I don't think it would be hard for IReady devs to do the same.

**Comment by cupiditys** [comment]
> > the code is obfuscated and i just dont want to handpick sorry
> 
> 
> 
> Hey I've actually was able to deobfuscate your code (no offence), and I'm a intermediete when it comes to coding/reading js/html/css so I don't think it would be hard for IReady devs to do the same.

yea i had to use pretty shitty obfuscation as better ones didn't seem to work but u still cant see too much?

**Comment by Ireadycoder** [comment]
whatever works, works.
