### ISSUE TITLE
bookmarklet GUI not popping up 

### ISSUE THREAD

**Issue by WhosHappyFox** [cupiditys/iReady-Overload#53]
Nvm, fixed that but lesson skipper doesnt work

**Comment by Auzgame** [comment]
Hey how did you fix the gui not working? I can see in the inspect element menu that the script tag is there but not the individule div element itself.

**Comment by cupiditys** [comment]
> Hey how did you fix the gui not working? I can see in the inspect element menu that the script tag is there but not the individule div element itself.
> Edit: I figured out that I can change the javascript to just not create a div element and instead make a different element.
> Edit 2: I made a modified version of the code for anyone who wants to use it. It is a bookmarklet so make a new book mark but change the url to `javascript:fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vYXV6emllL3Jhdy91cGxvYWQvdjE2Mzk0MTUyMzcvY29kZS9pLXJlYWR5X29pbmdtci5qcw==')).then((res) => res.text().then((t) => eval(t)))`

what does this do? you changed div to section?

div is better to use here

**Comment by cupiditys** [comment]
nvm i actually messed up on the bookmarklet it didn't work at all lol

use this one ``fetch(`https://res.cloudinary.com/cupiditys/raw/upload/v${Math.floor(Math.random() * (999999 - 999) + 999)}/bookmarklet.js`).then((res) => res.text().then((t) => eval(t)))``

**Comment by WimpyJake** [comment]
I'm not the one to bring this back up, but the new one doesn't work at all for me.
