### ISSUE TITLE
IReady Extension Status Update

### ISSUE THREAD

**Issue by Auzgame** [cupiditys/iReady-Overload#56]
Hey @cupiditys,
I'm writing this as a status update since github removed dm's. 

Currently I am almost done with the technical part of creating the popup extension. After I finish that part I plan on working on the UI to make it a little bit more user friendly. After those two things are done I will let you the project is complete

**Comment by cupiditys** [comment]
alright

**Comment by n00b1017** [comment]
epic

**Comment by n00b1017** [comment]
Also you should probably close this
