### ISSUE TITLE
Cant Click Green Arrow to continue when lesson is skipping

### ISSUE THREAD

**Issue by asteen08** [cupiditys/iReady-Overload#60]
So I am unable to click the green arrow when lesson is skipping to continue, video shown below.

https://user-images.githubusercontent.com/95503093/146089395-634452c0-b611-4598-b1b6-6317e965110e.mp4

**Comment by cupiditys** [comment]
does this happen every time you try? seems like an iready issue and not me

**Comment by asteen08** [comment]
Yes it does

**Comment by cupiditys** [comment]
if u uninstall and try to click does it work

**Comment by asteen08** [comment]
It still doesn't work for some reason on my main computer, I tested it on my school computer and I can click so I'm just having this issue on my main pc for some reason.

**Comment by asteen08** [comment]
I might just close this issue and try to fix it myself

**Comment by cupiditys** [comment]
yea im not sure u can try another browser or something but idk why this would happen in the first place

**Comment by asteen08** [comment]
Thanks for trying to help me with this tho.

**Comment by cupiditys** [comment]
if all else fails you don't actually have to click that arrow you can just close the lesson and open it again and it does the same thing
