### ISSUE TITLE
iready diagnostic

### ISSUE THREAD

**Issue by Vaporisdad** [cupiditys/iReady-Overload#61]
is the iready diagnostic fixed? i have one soon.

**Comment by Vaporisdad** [comment]
@cupiditys

**Comment by cupiditys** [comment]
no i was planning on doing it today but the guys account i was going to use completed the diagnostic before i could do it

**Comment by Vaporisdad** [comment]
I can give you a account VaporIsDaddy#4775

**Comment by cupiditys** [comment]
added

**Comment by Vaporisdad** [comment]
> added

Messaged you
