### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Ireadycoder** [cupiditys/iReady-Overload#63]
so now it is not giving the go button so i can fix the lesson it immediately goes to the text "tap the green arrow or try asking your teacher for help"

**Comment by cupiditys** [comment]
do it before the go button

**Comment by Ireadycoder** [comment]
doesnt work

**Comment by cupiditys** [comment]
send me a video of you trying ur probably doing something wrong

**Comment by Ireadycoder** [comment]
go ahead and close this issue
