### ISSUE TITLE
After what do I do?

### ISSUE THREAD

**Issue by TyrannoT-rex** [cupiditys/iReady-Overload#65]
I hate iready, but it's my grade. I followed all of the bookmarklet instructions, after i create the tab with the pasted javascript, what do __ do now?

**Comment by Ireadycoder** [comment]
you go to bookmark manager, create bookmark, paste code then save it, and then you go to iready and just click the bookmark and the menu will appear........ I tried explaining it best way possible

**Comment by Cyroarc** [comment]
I did it but it didn't work? can you try to explain it a bit more clearly?

**Comment by Cyroarc** [comment]
So, do I open the bookmarker in the tab or do I open it in iready?

**Comment by longnosepony** [comment]
hey i need help

**Comment by longnosepony** [comment]
i already made the bookmark but do i paste the code in iready menu or lesson same as Cyroarc

**Comment by Auzgame** [comment]
@longnosepony  no all you need to do is while your in the iready tab, click the bookmark and a menu should appear

**Comment by cupiditys** [comment]
either one is fine

**Comment by TyrannoT-rex** [comment]
@Auzgame i clicked star button and all it said was "edit bookmark" and "add to reading list"

**Comment by cupiditys** [comment]
> @Auzgame i clicked star button and all it said was "edit bookmark" and "add to reading list"

u press add bookmark after

**Comment by TyrannoT-rex** [comment]
does it skip the lesson
or give you minutes?

**Comment by TyrannoT-rex** [comment]
i kinda these those too and maybe the diagnostic

**Comment by cupiditys** [comment]
?

**Comment by TyrannoT-rex** [comment]
i learned how to do it tysm cupiditys
