### ISSUE TITLE
Fix Diagnostic Hack

### ISSUE THREAD

**Issue by SusyBo1** [cupiditys/iReady-Overload#66]
Diagnostic hack does not work please fix this @cupiditys I really need it
![image](https://user-images.githubusercontent.com/95867977/146584217-97b0f084-6c55-47ed-9b02-a96a4df543c2.png)

**Comment by SusyBo1** [comment]
i know i dont have a diagnostic but im going to have another one soon plz help

**Comment by Ireadycoder** [comment]
i gave him a acc, he is working on it.

**Comment by cupiditys** [comment]
done
