### ISSUE TITLE
Wont work on these math lessons

### ISSUE THREAD

**Issue by masssydoosy** [cupiditys/iReady-Overload#67]
So it wont work says Close n Press skip button again.

**Comment by masssydoosy** [comment]
I cant even send videos or images!

**Comment by masssydoosy** [comment]
Like the Lesson Matrix's Detective Dude Agency: Type Random Samples

**Comment by masssydoosy** [comment]
@cupiditys

**Comment by masssydoosy** [comment]
It says Close n Press skip button again. but when i do that it says: You're already skipping a lesson.

**Comment by masssydoosy** [comment]
HELPP

**Comment by masssydoosy** [comment]
@cupiditys

**Comment by masssydoosy** [comment]
answer plz

**Comment by Ireadycoder** [comment]
hey bro add me on discord @Ireadycoder#5309

**Comment by masssydoosy** [comment]
sure?

**Comment by Ireadycoder** [comment]
ill help you just add me on discord

**Comment by masssydoosy** [comment]
sent

**Comment by Ireadycoder** [comment]
cupid you can close this issue i solved it :)

**Comment by masssydoosy** [comment]
:D
