### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 8nine20** [cupiditys/iReady-Overload#69]
How does the diagnostic hack work like?

**Comment by 8nine20** [comment]
I havent tested it yet since I don't have a diagnostic as of right now

**Comment by Ireadycoder** [comment]
when you get one, I think he said you answer normally but it will auto get it right

**Comment by cupiditys** [comment]
every answer you put in is correct

**Comment by 8nine20** [comment]
I forgot to ask this question does this hack give you an insanely high score? or puts you on grade level

**Comment by Ireadycoder** [comment]
gets every question right for your grade, meaning different grades have different score ranges and all it will do is put you on your highest score range

**Comment by 8nine20** [comment]
What if I disable the diagnostic hack for some questions then I enable the diagnostic hack for some questions. Will that make my score very high or grade level ish

**Comment by cupiditys** [comment]
grade level

**Comment by 8nine20** [comment]
Alr one more question then I’ll stop asking questions. How many questions do I have to get correct to get a certain score? Like let’s say if I get 40 questions on the diagnostic correct what would my score be?

**Comment by cupiditys** [comment]
i don't know but it probably varies every diagnostic anyways

**Comment by cupiditys** [comment]
id probably only get like 10 wrong

**Comment by HypnoticLOL** [comment]
bro this is #69
