### ISSUE TITLE
I-ready Should STOP! this lol

### ISSUE THREAD

**Issue by WhatHaveIGottenInto2020** [cupiditys/iReady-Overload#7]
I ready overload dashboard isn't popping up now :/. Can someone help me with this?

**Comment by cupiditys** [comment]
have you downloaded the newest version cuz they patched the old one

**Comment by cyber1109** [comment]
the hacks wont work I tried it and the skipper wont work i have installed it like 7 other times it still wont work

**Comment by cupiditys** [comment]
i checked yesterday and it worked, unless iready changed something since yesterday it should be good

can you send me a video of you trying and it not working cuz im not at my pc rn

**Comment by cyber1109** [comment]
cant sorry i can send screen shots of like the after math

**Comment by cupiditys** [comment]
lemme see i can get on pc in a few mins

**Comment by cyber1109** [comment]
k

**Comment by cyber1109** [comment]
you see the problom? or is it just me

**Comment by cupiditys** [comment]
gonna be like 15 more mins

**Comment by masssydoosy** [comment]
im having the same issue newest version

**Comment by cyber1109** [comment]
> gonna be like 15 more mins

ok

**Comment by cupiditys** [comment]
shit i just realized i committed the wrong version to github

i'll fix as soon as i can

**Comment by cupiditys** [comment]
the version i commuted doesn't work

**Comment by masssydoosy** [comment]
ok!

**Comment by cyber1109** [comment]
> 

wow you got it right on the 15 min mark

**Comment by cyber1109** [comment]
> the version i commuted doesn't work

sooooooo what dose work

**Comment by cupiditys** [comment]
lesson skipper fixed, https://github.com/cupiditys/iReady-Overload/tree/main/lessonSkipper
