### ISSUE TITLE
Not issue kinda just comment

### ISSUE THREAD

**Issue by HypnoticLOL** [cupiditys/iReady-Overload#71]
ok so first of all I made a github with ur menu but transparent ui, changed it to go to my website and say "Hypnotics menu" but the first think i do is link ur github, and how u get the anti skipper to press buttons EX: it goes into a lesson for u injects lesson skipper code into it leaves dose the code again and repeat?

**Comment by cupiditys** [comment]
document.getElementById("whatever-the-close-button-is-called").click()

**Comment by HypnoticLOL** [comment]
yes I know that, I read and studied all your code so I know that, I just wanna know how you get the names?

**Comment by cupiditys** [comment]
ctrl shift i, click on below button and then the lesson close button
![image](https://user-images.githubusercontent.com/66990287/147798095-95855661-6426-4707-9182-54fac74746e0.png)
id is right there
![image](https://user-images.githubusercontent.com/66990287/147798108-fb155563-43ba-4d60-b6b4-4952eb46d896.png)

**Comment by HypnoticLOL** [comment]
so I have this
setInterval(lol, 10000)
function lol() {
    document.getElementById("btn-footer-TO_DO").click()
    document.getElementById("system-activity-910216c1-28ef-485e-a248-716a53856753").click()
    document.getElementById("lesson-splash-continue-button-button").click()
    document.getElementById("lesson-close").click()
}
and when i use it it dose the first 2 but then stops at the continue button, do you know how to fix this?

**Comment by cupiditys** [comment]
r u sure its an id and not class

**Comment by HypnoticLOL** [comment]
let me check

**Comment by HypnoticLOL** [comment]
no its id and the leave button isnt workin
![Screenshot 2021-12-30 9 22 24 PM](https://user-images.githubusercontent.com/96861065/147801337-cc33cb46-3d51-4c75-9c71-f3cf4498681c.png)
g

**Comment by HypnoticLOL** [comment]
was just messing with the buttons sorry

**Comment by HypnoticLOL** [comment]
and I see with the leave button you are using reading, I am on math. although it dosnt work for either.

**Comment by cupiditys** [comment]
yea idk i dont have any lessons like that

**Comment by HypnoticLOL** [comment]
heres the iframe for the lesson
https://cdn.i-ready.com/instruction/phoenix/master/147/?csid=DI.MATH.MS.6.0027.phx.10_910216c1-28ef-485e-a248-716a53856753_M_math&type=TUTORIAL#/lesson/math/DI_MATH_MS_6_0027_10

**Comment by HypnoticLOL** [comment]
in an old version of the iready overload menu, when you click the skip lesson and answer 1 question it auto leaves the lesson, thats what i need to know how to do if u could give me that code.

**Comment by HypnoticLOL** [comment]
oh and if you have time, could you check out my menu, I remade it so its cooler than just black and white.

**Comment by cupiditys** [comment]
where is it

**Comment by cupiditys** [comment]
> in an old version of the iready overload menu, when you click the skip lesson and answer 1 question it auto leaves the lesson, thats what i need to know how to do if u could give me that code.

this is literally all it is
```
html5Iframe.contentWindow.document.getElementById("lesson-close").click()
html5Iframe.contentWindow.document.getElementsByClassName("yesButtonConfirmModal closeModal")[0].click()
```

**Comment by cupiditys** [comment]
> yes, its id and the leave button isnt working, heres the screenshot ![Screenshot 2021-12-30 9 22 24 PM](https://user-images.githubusercontent.com/96861065/147801337-cc33cb46-3d51-4c75-9c71-f3cf4498681c.png)

in that example u shouldnt get it by id since it probably is different each time so this would be better
```
document.querySelector('[aria-label="lessonActivity Clickable"]').click()

**Comment by cupiditys** [comment]
also if youre running from console u have to be in right context
![image](https://user-images.githubusercontent.com/66990287/147836219-67aa3a38-719f-49a7-967a-40f1e1c8f9d2.png)

**Comment by HypnoticLOL** [comment]
> where is it

its my only github thing on my account

**Comment by HypnoticLOL** [comment]
> where is it

heres the menus link https://github.com/HypnoticLOL/Hypnotics-Menu

**Comment by cupiditys** [comment]
personally i prefer gray/black sorry but some people may like colors

**Comment by HypnoticLOL** [comment]
thanks
