### ISSUE TITLE
Catch 

### ISSUE THREAD

**Issue by Zanizkyo** [cupiditys/iReady-Overload#72]
Will school catch me if I use the iready bookmarklet?

**Comment by HypnoticLOL** [comment]
> Will school catch me if I use the iready bookmarklet?

dont get caught using it, they can see it on gogardian securly or anything, so just use it in caution, but no the school wont fucking have powers and sence when u use it and curb stomp you.

**Comment by cupiditys** [comment]
wouldnt recommend using on school wifi if you're trying to stay safe (since they can view all network traffic and will know if you use it) but other than that its alright

**Comment by Zanizkyo** [comment]
Can you atleast make a hack that shows your diagnostic score while you’re
doing the test?

**Comment by TheFinality** [comment]
impossible

**Comment by cupiditys** [comment]
actually insanely easy as long as questions are worth same score across all diagnostics (not sure if thats the case tho)

**Comment by WhatHaveIGottenInto2020** [comment]
> wouldnt recommend using on school wifi if you're trying to stay safe (since they can view all network traffic) but other than that ur fine

Hotspot should keep you safe (I don't think they can look through ur browser with some wifi that they don't own)
