### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by SusyBo1** [cupiditys/iReady-Overload#73]
Can you make Math Learning Game Hacks? ex: infinite cash in Cupcake?

**Comment by cupiditys** [comment]
yes its very easy but why

**Comment by SusyBo1** [comment]
why not? (also because I want infinite cash in cupcake/pizza)

**Comment by SusyBo1** [comment]
plz just add learning game hacks plzzzz

**Comment by cupiditys** [comment]
for what games

**Comment by SusyBo1** [comment]
Cupcake and Pizza please :)

**Comment by cupiditys** [comment]
don't have those

**Comment by SusyBo1** [comment]
I can give you an account :)

**Comment by cupiditys** [comment]
> @cupiditys I can give you an account :)

send it to cupiditysxd@gmail.com

**Comment by SusyBo1** [comment]
Sent
