### ISSUE TITLE
Rquest 

### ISSUE THREAD

**Issue by Auzgame** [cupiditys/iReady-Overload#75]
Hi, so as you know I'm working on the extension, and I just want to know if you could send me the code deobfuscated. If so could you email me the code.
[Email link](mailto:auzziescibelli@gmail.com)

**Comment by cupiditys** [comment]
what part are you working on? i can send just the design if you want

**Comment by Auzgame** [comment]
I'm working on the injection part of the code, and I want to make as close to yours as possible for easy updates. The functions like skip lesson and minutes would do. Thx.

**Comment by cupiditys** [comment]
the injection already works fine?

**Comment by Auzgame** [comment]
Yes. I just need the code to do the actually "faking out" iready part

**Comment by Auzgame** [comment]
Hey, I noticed you closed this thread, and you didn't send the code. Are you going to send the code?

**Comment by Barnac1ed** [comment]
> Hey, I noticed you closed this thread, and you didn't send the code. Are you going to send the code?

They probably mean no lol
