### ISSUE TITLE
Diagnostinc mode didnt do anything.

### ISSUE THREAD

**Issue by RealZeroXtrem** [cupiditys/iReady-Overload#76]
i started my new diagnostic for school and clicked the "Enable" button on the diagnostic hack, and went through the entire diagnostic slowly without speeding through as not to make it think i was rushing like it said and got to the end and i got a 282 score

**Comment by cupiditys** [comment]
very weird, every time ive tried its worked. maybe doesnt work for every diagnostic idk

**Comment by Auzgame** [comment]
@RealZeroXtrem  was there an error in the console?

**Comment by RealZeroXtrem** [comment]
i didnt look in the console while i did it

**Comment by TheFinality** [comment]
this doesnt work, check my reddit post. it simply edits a variable in the request body, but the answers are still checked on the backend.

**Comment by masssydoosy** [comment]
@cupiditys Are yousure when the diagnostic hack is fixed?

**Comment by cupiditys** [comment]
nah im not sure

**Comment by Ireadycoder** [comment]
@cupiditys i can get u another account

**Comment by cupiditys** [comment]
> @cupiditys i can get u another account

with a diagnostic?

**Comment by Ireadycoder** [comment]
yea

**Comment by poopyhead121** [comment]
zamn

**Comment by asteen08** [comment]
I have an account with a reading diagnostic, will it work?

**Comment by Tripp-dripp** [comment]
y e s

**Comment by cupiditys** [comment]
obviously 

send to my email cupiditysxd@gmail.com
