### ISSUE TITLE
Is this suppose to happen with "How to avoid being AFK-Kicked"?

### ISSUE THREAD

**Issue by SusyBo1** [cupiditys/iReady-Overload#77]
![image](https://user-images.githubusercontent.com/95867977/148404782-f147af57-cd6e-4f64-8728-b7b8843376d8.png)
I think there's a problem with the code for "How to avoid being AFK-Kicked"

plz help

**Comment by cupiditys** [comment]
where did you try to use it and are you sure you copied it right

**Comment by SusyBo1** [comment]
I entered it in the dashboard

**Comment by SusyBo1** [comment]
Lol, I entered it wrong sorry :)
