### ISSUE TITLE
The goddamn code

### ISSUE THREAD

**Issue by HypnoticLOL** [cupiditys/iReady-Overload#78]
I need the origanal non fucking modified just the code to open the menu non obfuscated and no of the `exsample`+'exsampe' pls if u want to email me like the other guy my email is below but pls I would like to make one myself for real not just ripping off ur menu
bigmanpreston620@gmail.com

**Comment by cupiditys** [comment]
what r u even gonna add

**Comment by HypnoticLOL** [comment]
imma try to add the anti afk as a button and a thing that gives you the iframe just in case lesson skipper dosnt work so u can get the correct answer in the iframe

**Comment by HypnoticLOL** [comment]
I have all the code planned and I know how ur menu works but I would like to add these things

**Comment by HypnoticLOL** [comment]
> what r u even gonna add
[main.zip](https://github.com/cupiditys/iReady-Overload/files/7834173/main.zip)

nevermind I have the code from your chrome webstore exstesion 
its at the top if anyone wants it
