### ISSUE TITLE
iready overload diagnostic

### ISSUE THREAD

**Issue by Jaysplatt24** [cupiditys/iReady-Overload#79]
the diagnostic HACK DID NOT WORK FOR ME. i used it and got a 417 score bru like really they said you'll get every answer right.

**Comment by Jaysplatt24** [comment]
i still have my math one should i try it again or don't

**Comment by Ireadycoder** [comment]
dont answer questions to quickly or it will makee score low

**Comment by cupiditys** [comment]
> i still have my math one should i try it again or don't

i wouldnt i dont think it actually works

ill remake it to work i just need an account with a diagnostic first

**Comment by by1egend251** [comment]
bro i really  just found out and ive been using it 80% of the test

**Comment by by1egend251** [comment]
is there another diagnostic script

**Comment by by1egend251** [comment]
nvm bro i actually leveled up it worked ty maybe it doesnt work on certain diagnostics it worked for me

**Comment by quantem** [comment]
it worked in the morning for me, i jumped 100 points on my reading but on my math i dropped 100 points, idk what happened but ima just try to do it fr cus i need this grade.
