### ISSUE TITLE
Doesn't work with reading lessons.

### ISSUE THREAD

**Issue by ionlyusegithubformcmods** [cupiditys/iReady-Overload#80]
Worked fine with math ones but it cant skip reading lessons

**Comment by HypnoticLOL** [comment]
this happend to me try to do your best and try next lesson

**Comment by cupiditys** [comment]
> Worked fine with math ones but it cant skip reading lessons

wdym by doesnt work? can u send a video

**Comment by cupiditys** [comment]
if you mean close reading then yea it doesnt but ive tested plenty of times with reading and it works

**Comment by cupiditys** [comment]
also make sure to read popup closely, some lessons have different instructions

**Comment by Ireadycoder** [comment]
most of the math u have to skip without having to go back in the lesson, prob what hes doing wrong
