### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Idkmank** [cupiditys/iReady-Overload#82]
Did you fix diagnostic hack I have one on Monday. Also do you have a hack for iready master checks? I need one

**Comment by cupiditys** [comment]
no, ive already looked and im pretty sure a mastery check hack is not possible (at least one that works with all) since they are made by the county and even hosted on their servers

**Comment by Idkmank** [comment]
Alr

**Comment by Idkmank** [comment]
Also for the diagnostic hack you wanna use my account and do it?

**Comment by cupiditys** [comment]
alright sure

**Comment by cupiditys** [comment]
just email me info

**Comment by Idkmank** [comment]
What’s ur email

**Comment by cupiditys** [comment]
cupiditysxd@gmail.com
