### ISSUE TITLE
question

### ISSUE THREAD

**Issue by HypnoticLOL** [cupiditys/iReady-Overload#83]
how do you find the iframe for the iready shit, like so I can display it on the menu. I just need the code for that i have the menus code

**Comment by HypnoticLOL** [comment]
this bookmarklet has it but I dont know how to get it myself 
`javascript:(function () { var script = document.createElement('script'); script.src="//cdn.jsdelivr.net/npm/eruda"; document.body.appendChild(script); script.onload = function () { eruda.init() } })();`

**Comment by cupiditys** [comment]
i'm not sure what you mean? you can reference the iframe with "html5Iframe"

**Comment by HypnoticLOL** [comment]
ok so im fucking tired im confused how to exsplain it, when you go into a lesson it loads an iframe and what id like to do is get that iframe link and display it on the menu

**Comment by HypnoticLOL** [comment]
like thi
![Screenshot 2022-01-08 10 37 39 PM](https://user-images.githubusercontent.com/96861065/148669683-b0b45a8e-7320-47c1-bd68-17b3ae925da3.png)
s

**Comment by cupiditys** [comment]
html5Iframe.src?

**Comment by HypnoticLOL** [comment]
I barley know fucking javascript I dont know what the fuck to do with that but thanks

**Comment by cupiditys** [comment]
its not complicated like in ur menu u can just do 
```
`Iframe Link: ${document.getElementById("html5Iframe").src}`
```

**Comment by HypnoticLOL** [comment]
k imma try that

**Comment by HypnoticLOL** [comment]
so im using an `<h3>Iframe Link: <span id=""></span>` will that work with the code you gave me?

**Comment by HypnoticLOL** [comment]
yeah when I use that it shows its blank and dosnt display it on the menu

**Comment by HypnoticLOL** [comment]
this is what the menu dose
![Screenshot 2022-01-09 8 24 19 PM](https://user-images.githubusercontent.com/96861065/148711747-48ead3c0-8f54-4bd9-a091-b74aa5f706d4.png)
