### ISSUE TITLE
Obfusacate

### ISSUE THREAD

**Issue by HypnoticLOL** [cupiditys/iReady-Overload#84]
its late and im tired, but ive tried to obfusicate your code and it dosnt work, im gonna release it to my github soon and idk how to do this shit, what shit do u use?

**Comment by cupiditys** [comment]
literally just obfuscator.io lol but make sure to edit the settings and test it after cuz some don't work

**Comment by poopyhead121** [comment]
i made my own obfuscator lo

**Comment by HypnoticLOL** [comment]
like what settings? like could u pls screenshot the settings u use

**Comment by HypnoticLOL** [comment]
nvm I found em just turn off string arrays
