### ISSUE TITLE
Diagnostic

### ISSUE THREAD

**Issue by longnosepony** [cupiditys/iReady-Overload#85]
i'm taking it right now and if you use the diagnostic hack won't it seem obvious that your cheating? since you get all of them right

**Comment by Cyroarc** [comment]
i agree longnose pony xD why cant you change it to like 89%?

**Comment by longnosepony** [comment]
yeah like the lesson skipper

**Comment by Cyroarc** [comment]
yeah

**Comment by WhatHaveIGottenInto2020** [comment]
I have a diagnostic if you would like to use it for coding
Also I think @cupiditys should add a thing at the top of the screen saying what you would like your score to be so it wouldn't b so suspicious, kinda like the quiz results at the end, where there is a prompt that tells you what number you want your diagnostic to show. I'm horrible at coding but this is just a suggestion

**Comment by SexyLittlePony** [comment]
@longnosepony am i cute ;)

**Comment by longnosepony** [comment]
leave, this is only for iready

**Comment by longnosepony** [comment]
stop getting off topic

**Comment by SexyLittlePony** [comment]
im coooliooooooooooooooool

[RICKROLED.txt](https://github.com/cupiditys/iReady-Overload/files/7841248/RICKROLED.txt)

**Comment by longnosepony** [comment]
@cupiditys i'm taking it right now and if you use the diagnostic hack won't it seem obvious that your cheating? since you get all of them right

**Comment by longnosepony** [comment]
@SexyLittlePony i said leave

**Comment by longnosepony** [comment]
unless you need to talk to cupiditys

**Comment by SexyLittlePony** [comment]
@cupiditys watch my video its my face 
https://www.youtube.com/watch?v=a6pbjksYUHY

**Comment by longnosepony** [comment]
it's a rickroll

**Comment by longnosepony** [comment]
i can feel my rickroll senses tingling

**Comment by longnosepony** [comment]
No

**Comment by longnosepony** [comment]
and i said leave

**Comment by longnosepony** [comment]
@cupiditys there is an online troll bothering your customers. We would appreciate it if you kicked or banned them from this hack if you can

**Comment by cupiditys** [comment]
> @cupiditys there is an online troll bothering your customers. We would appreciate it if you kicked or banned them from this hack if you can

who
