### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by HypnoticLOL** [cupiditys/iReady-Overload#88]
What will your licence mean for my menu? dose it mean I cant credit myself in the menu? or dose it mean I have to take it down 100%?

**Comment by cupiditys** [comment]
just means you have to leave the credit in the gui, u can still use it

**Comment by HypnoticLOL** [comment]
@cupiditys 

> just means you have to leave my credit in the gui, u can still use it

dose this violate the licence? 
![image](https://user-images.githubusercontent.com/96861065/149223886-2a7103dd-9ee1-4ae5-976d-22251b01fab1.png)

**Comment by cupiditys** [comment]
no

**Comment by HypnoticLOL** [comment]
thx, idk why people delete ur shit I will always credit you
