### ISSUE TITLE
wont skip math lesson

### ISSUE THREAD

**Issue by aaaaaa2134456** [cupiditys/iReady-Overload#89]
Ok so when I tried to skip a math lesson it gives me the instruction to exit the lesson and click skip again, but when I do so it doesn't work and says "you're already skipping a lesson"
![image](https://user-images.githubusercontent.com/61943320/149044154-8eb9ec34-bd65-4de6-b558-a4e0acdb1174.png)
![image](https://user-images.githubusercontent.com/61943320/149044186-a2098fdb-ac6d-4943-8935-3ac82386307f.png)

**Comment by RealZeroXtrem** [comment]
on some you just click back into the lesson

**Comment by HypnoticLOL** [comment]
Ive seen this before, reload the page and keep trying or do what ever cupidity days he will prob restpond but thats how I did it

**Comment by cupiditys** [comment]
are you opening the lesson again? it says not to (you should click skip on the home page)

**Comment by aaaaaa2134456** [comment]
wait so i should click skip on the home page?

**Comment by aaaaaa2134456** [comment]
im going to test it rn

**Comment by cupiditys** [comment]
yes

**Comment by aaaaaa2134456** [comment]
ok i see, it worked

**Comment by aaaaaa2134456** [comment]
i was going back into the lesson that's why
