### ISSUE TITLE
Lesson Skip patched?

### ISSUE THREAD

**Issue by JuiceKidd** [cupiditys/iReady-Overload#9]
Both extension and javascript versions don't work, minutes do work but I'm pretty sure only the extension one works. When loading the menu bookmarklet it tends to disappear when loading a lesson. When loading in a lesson it will disappear within a second.

**Comment by JuiceKidd** [comment]
dont know what I did but the bookmarklet works now doesn't disappear but lesson skip ends in a 401 error in console

**Comment by cupiditys** [comment]
fixed, https://github.com/cupiditys/iReady-Overload/tree/main/lessonSkipper
