### ISSUE TITLE
diagnostic

### ISSUE THREAD

**Issue by Ireadycoder** [cupiditys/iReady-Overload#90]
just wanted to let you know the diagnostic hack works, just some don't for some reason. mine always worked but i see other people sometimes not working for them.

**Comment by cupiditys** [comment]
yea its weird ill probably just add a disclaimer or something saying it doesn't work on all diagnostics cuz i looked and i doubt there's any other way to make a hack

**Comment by Ireadycoder** [comment]
alright, just wanted to make sure you knew but ill close this now.
