### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by trickyiscool98** [cupiditys/iReady-Overload#92]
the diagnostic hack does not work. please fixt it, my score is 442. and yes, every minute i answered the questions.

**Comment by cupiditys** [comment]
> the diagnostic hack does not work. please fixt it, my score is 442. and yes, every minute i answered the questions.

does not work on all diagnostics, i will add a disclaimer in next release

**Comment by cupiditys** [comment]
> > 
> 
> does not work on all diagnostics, i will add a disclaimer in next release

where did you get this from

**Comment by cupiditys** [comment]
> Yeah, it just closes iready with an error when launching, bans you too sometimes, might be patched.

where did you get this from

**Comment by WhatHaveIGottenInto2020** [comment]
> the diagnostic hack does not work. please fixt it, my score is 442. and yes, every minute i answered the questions.

Does it refresh after every brain break?
one of my friends got a high score because he re-enabled it after every brain break

**Comment by cupiditys** [comment]
> > the diagnostic hack does not work. please fixt it, my score is 442. and yes, every minute i answered the questions.
> 
> Does it refresh after every brain break? one of my friends got a high score because he re-enabled it after every brain break At least that's what he told me so... :|

no
