### ISSUE TITLE
i have 3 ideas of hacks you could add

### ISSUE THREAD

**Issue by vch999** [cupiditys/iReady-Overload#93]
1. Dupe/add minutes
2. get the answers for questions in a lesson/ Skip lesson (perfect score)
3. infinite coins/ add or set coins

**Comment by vch999** [comment]
> 

Yeah, ik

**Comment by cupiditys** [comment]
> * Dupe/add minutes
> * get the answers for questions in a lesson/ Skip lesson (perfect score)
> * infinite coins/ add or set coins

1. already working on that, pretty close to done
2. that already exists? it lets you choose score
3. probably not possible but never looked into it

**Comment by vch999** [comment]
okay, i thought that number 2 would give a rlly low score, lol

**Comment by cupiditys** [comment]
> okay, i thought that number 2 would give a rlly low score, lol Update: number 2 does not let me chose score, and its kinda glichy

wdym bruh

**Comment by SusyBo1** [comment]
Infinite Coins Sounds Cool :D

**Comment by vch999** [comment]
is it supposed to prompt?

**Comment by cupiditys** [comment]
> is it supposed to prompt?

when ur on a quiz and you press skip it will prompt asking what score you want

**Comment by cupiditys** [comment]
> > is it supposed to prompt?
> 
> when ur on a quiz and you press skip lesson button it will prompt asking what score you want

**Comment by vch999** [comment]
> > > is it supposed to prompt?
> > 
> > 
> > when ur on a quiz and you press skip lesson button it will prompt asking what score you want

it doesn't do anything

**Comment by vch999** [comment]
3. there could be a script that gets triggered when ur supposed to get coins, maybe find a way to use that trigger thing?

**Comment by vch999** [comment]
nvm number 2 works

**Comment by X2isme** [comment]
new account btw
