### ISSUE TITLE
Can you skip Mastery Check Lessons?

### ISSUE THREAD

**Issue by SusyBo1** [cupiditys/iReady-Overload#95]
![image](https://user-images.githubusercontent.com/95867977/149523308-42a57313-633f-45d2-b693-081091698277.png)

**Comment by SusyBo1** [comment]
Please help I have one right now!!!!!!

**Comment by SusyBo1** [comment]
Nvm I already did it

**Comment by WhatHaveIGottenInto2020** [comment]
wait what's even a "mastery check"? My school never did any of those lol
