### ISSUE TITLE
Doesent work

### ISSUE THREAD

**Issue by hharrell3661** [cupiditys/iReady-Overload#98]
When i try to skip a reading lesson it does not work, but on math it works perfectly fine.

**Comment by cupiditys** [comment]
read what the nogficiation says it probably says "close the lesson and press skip button" because its a different type of lesson and youre probably trying to open the lesson again and click it

**Comment by cupiditys** [comment]
pinning this so perople stop making issues about it

**Comment by HypnoticLOL** [comment]
damn I thought he was lying but thank god its the weekend

**Comment by HypnoticLOL** [comment]
even with mine its broken

**Comment by HypnoticLOL** [comment]
in console it prompts 40
![Screenshot 2022-01-14 10 43 55 PM](https://user-images.githubusercontent.com/96861065/149609259-72190b2d-c2fd-4ba2-8fa7-c0b1d823ff76.png)
4

**Comment by HypnoticLOL** [comment]
@cupiditys  I fixed it

**Comment by HypnoticLOL** [comment]
heres the code to your menu fixed, when using method 1 it alerts a blank alert
(obfusicated
[obfuscated.txt](https://github.com/cupiditys/iReady-Overload/files/7874279/obfuscated.txt)
)

**Comment by HypnoticLOL** [comment]
![Screenshot 2022-01-14 11 04 40 PM](https://user-images.githubusercontent.com/96861065/149609732-ff4a0f22-2408-4312-a280-076b8693e2bd.png)
prompts error but I dont give a shit it works.

**Comment by HypnoticLOL** [comment]
are you fucking illiterate?
