### ISSUE TITLE
HOW TO FIX THE READING NOT WORKING

### ISSUE THREAD

**Issue by HypnoticLOL** [cupiditys/iReady-Overload#99]
I fucking fixed it all it dose is when using method 1 gives another alert, if u want to credit me u can if u dont i dont give a shit,
download for the fix 
[obfuscated.txt](https://github.com/cupiditys/iReady-Overload/files/7874291/obfuscated.txt)

heres the code to fix it
![Screenshot 2022-01-14 11 15 09 PM](https://user-images.githubusercontent.com/96861065/149609942-d9323e59-ea74-4cc8-b143-d33047ab8116.png)

works although it prompts this in console

![Screenshot 2022-01-14 11 04 40 PM](https://user-images.githubusercontent.com/96861065/149609951-d2f1bf7d-17d1-44d6-b3f7-d1a671af1cf8.png)

**Comment by cupiditys** [comment]
what does this do

**Comment by cupiditys** [comment]
the reading already works fine its just because people are retarded and cant read the popups

**Comment by cupiditys** [comment]
i dont think anyone used it

**Comment by HypnoticLOL** [comment]
lol it was kinda usless but kinda cool so I added it back to mine, if u want anything on my menu changed tell me ill do it cuz without you the menu would be fucked.
